### ISSUE TITLE
真的有效！

### ISSUE THREAD

**Issue by AlexanderMisel** [URenko/Accesser#1]
感谢建立此项目。能不能简单介绍一下原理呢？这样大家用着还放心点。是如何避免网站名被检测的呢？

我在你基础上删掉了一些我认为没必要的代码。不从网上下hosts，而是自己配，我觉得这样比较好。无需在config文件配，直接配目录下的hosts文件就好了。

**Comment by URenko** [comment]
@AlexanderMisel TLS本来就没server_name的要求，[RFC 6066](https://tools.ietf.org/html/rfc6066#section-3)也只是用MAY、RECOMMENDED这种说法要求server_name，所以只要不包含server_name就好了。
而[RFC 5246](https://tools.ietf.org/html/rfc5246#section-7.4.2)要求服务器必须发送证书，对于维基、Pixiv这些站点在没有server_name的情况下也发送正确域名的证书，所以可以校验证书，保证安全性。

**Comment by URenko** [comment]
我觉得自己配比较麻烦，新增加域名要重新搞hosts，所以采取在网上hosts基础上通过setting.ini修改的办法

**Comment by AlexanderMisel** [comment]
已分享这种方法
