### ISSUE TITLE
Problem when the DNS query failed

### ISSUE THREAD

**Issue by URenko** [URenko/Accesser#10]
When the DNS query failed, the program will be blocked, and the CPU usage is high.
5a51a8ef9242225da4003210226de423363a28fa is just a temporary solution to avoid DNS query failed. When you want to reappear it, you have to roll it back. And you can test www.tumblr.com as it need many DNS queries.

**Comment by SeaHOH** [comment]
1. 收到 host 的第一个查询时，先预设一个值存入缓存。
1. 后续的相同查询检测到预设值就等待，直至有结果返回。
1. 查询失败，缓存一个失败结果，再向请求连接返回错误页面。
1. 缓存应支持过期，查询失败后可以设置一个较短的过期时间，以便重新查询。

**Comment by URenko** [comment]
感谢，但是感觉还是治标不治本

**Comment by SeaHOH** [comment]
如果你的目标是永不失败，这是不可能的，这个处理流程我也是大量摸索和学习后才理解的。

**Comment by URenko** [comment]
这的确是一个很好的方案，但是我想知道CPU占用高的原因😂，感觉问题不在于此。

**Comment by SeaHOH** [comment]
重点在 CPU 占用，那么要检查一下协程是否处理好了，一般都是没处理好造成阻塞。

但你这里的问题好像就是我上面讲的流程处理不好造成的，如果没有那个 `Lock` 就会同时启动大量相同的查询，然后也就能理解 CPU 占用为啥会飙升。

但是那个 `Lock` 是不适合用在这里的，因为也会阻止所有其它域名的查询，人为造成延迟，影响使用体验。
https://github.com/URenko/Accesser/blob/1a9a85d76b4a2f522ea0a0ebe101eedee580757f/accesser.py#L254-L260

**Comment by URenko** [comment]
是的，那个`Lock`只能是临时解决方法。
但是我觉得大量的DNS查询只是诱因，因为即使在CPU占用飙升后较长时间停止访问，CPU占用依然不会下降。
协程的处理是重点要关注的，我也觉得问题是这里。
有时间的话再改流程看看。

**Comment by SeaHOH** [comment]
才注意你的代理并没有使用协程，这会导致性能问题。

> 但是我觉得大量的DNS查询只是诱因，因为即使在CPU占用飙升后较长时间停止访问，CPU占用依然不会下降。

这可能是 aioh2 的问题。

**Comment by URenko** [comment]
考虑到aioh2更新较慢（[pypi上的已无法在python3.7运行](https://github.com/decentfox/aioh2/pull/20)），doh-proxy亦不活跃，将考虑使用[dnscrypt-proxy](https://github.com/jedisct1/dnscrypt-proxy)（支持DoH和dnscrypt协议）作为DNS解决方案。

由doh-proxy引起的bug一般情况下将不修复。
