### ISSUE TITLE
WebUI无法打开，我是否有什么未配置

### ISSUE THREAD

**Issue by RemKeeper** [URenko/Accesser#106]
![image](https://user-images.githubusercontent.com/78486275/192272332-fce4b379-3058-41ae-83f1-81b24cba0838.png)
系统版本如上

![image](https://user-images.githubusercontent.com/78486275/192272090-a3f2d478-410b-4fef-885e-73c62ac76533.png)
Python版本3.8.10

![image](https://user-images.githubusercontent.com/78486275/192272272-dcda91a5-09a4-42e6-80bc-38834f310847.png)
![image](https://user-images.githubusercontent.com/78486275/192272433-844209ed-c841-4c05-9613-708fe4fbab97.png)
按照教程下载的文件

![image](https://user-images.githubusercontent.com/78486275/192272777-bb01429c-f02b-4fd5-8abc-d6b1642b6216.png)
编辑profile文件设置pac

![image](https://user-images.githubusercontent.com/78486275/192272916-85fd8853-bd83-4b66-b0ac-c34db7ed957b.png)
端口已放行

![image](https://user-images.githubusercontent.com/78486275/192273421-3d39ce12-ee32-4ce9-8183-43993631ad4c.png)
运行程序后提示

![image](https://user-images.githubusercontent.com/78486275/192273690-c6b3f23e-2699-4022-8045-97af4c0c8e19.png)
WebUI无法打开

未找到accesser.log

**Comment by URenko** [comment]
你是在Linux中运行的程序？然后在Windows中访问？
你要修改`config.json`里的`server`的`address`，参考https://github.com/URenko/Accesser/wiki/%E8%AE%BE%E7%BD%AE%E8%AF%B4%E6%98%8E ，如果还不行或许你可以先在Linux中访问看看
以及，你需要在`config.json`中添加日志路径
