### ISSUE TITLE
一键程序生成的证书重复

### ISSUE THREAD

**Issue by Longway22** [URenko/Accesser#112]
我没有Windows电脑，至少在macOS上面编译出来的一键程序每次启动都生成不同的根证书，而且该证书不在accesser可执行程序所在的目录，不知道在哪里。

我想Windows的情况也是一样，每次启动都重新生成并导入根证书，这样就会造成系统证书库里时间长了就会出现很多Accesser证书。

解决方法：根证书应该像像 config.toml 和 Accesser.log 一样生成在可执行文件的目录，这样只要可执行程序位置没变就只会生成一次证书。

**Comment by URenko** [comment]
我并不理解你说的在macOS上的一键程序，因为一键程序是为Windows所设计的，也许你指的是在macOS下用PyInstaller所生成的程序？
在Windows上，一键程序所生成的根证书会储存在Windows证书储存区，这与一些抓包软件（如Fidder）是一致的，启动时会从中提取，因此理论上只会生成一次根证书。对macOS未设计类似的机制。
对于macOS，推荐的使用方法是作为Python库安装或是在clone/下载后调用，此时根证书会存储在accesser目录下。
