### ISSUE TITLE
最新版本，我自己用源码编译的程序运行后报错“httpx is not available”

### ISSUE THREAD

**Issue by lxfly2000** [URenko/Accesser#113]
Win10
Python 3.11.2
```
Name: pyOpenSSL
Version: 23.0.0
Summary: Python wrapper module around the OpenSSL library
Home-page: https://pyopenssl.org/
Author: The pyOpenSSL developers
Author-email: cryptography-dev@python.org
License: Apache License, Version 2.0
Location: C:\Users\Yueyu\AppData\Local\Programs\Python\Python311\Lib\site-packages
Requires: cryptography
Required-by: 
---
Name: tld
Version: 0.13
Summary: Extract the top-level domain (TLD) from the URL given.
Home-page: https://github.com/barseghyanartur/tld
Author: Artur Barseghyan
Author-email: artur.barseghyan@gmail.com
License: MPL-1.1 OR GPL-2.0-only OR LGPL-2.1-or-later
Location: C:\Users\Yueyu\AppData\Local\Programs\Python\Python311\Lib\site-packages
Requires: 
Required-by: 
---
Name: dnspython
Version: 2.3.0
Summary: DNS toolkit
Home-page: https://www.dnspython.org
Author: Bob Halley
Author-email: halley@dnspython.org
License: ISC
Location: C:\Users\Yueyu\AppData\Local\Programs\Python\Python311\Lib\site-packages
Requires: 
Required-by: 
---
Name: pyinstaller
Version: 5.8.0
Summary: PyInstaller bundles a Python application and all its dependencies into a single package.
Home-page: https://www.pyinstaller.org/
Author: Hartmut Goebel, Giovanni Bajo, David Vierra, David Cortesi, Martin Zibricky
Author-email: 
License: GPLv2-or-later with a special exception which allows to use PyInstaller to build and distribute non-free programs (including commercial ones)
Location: C:\Users\Yueyu\AppData\Local\Programs\Python\Python311\Lib\site-packages
Requires: altgraph, pefile, pyinstaller-hooks-contrib, pywin32-ctypes, setuptools
Required-by: 
```

**Comment by lxfly2000** [comment]
报错信息
2023-03-07 23:04:16 ERROR    asyncio: Task exception was never retrieved
future: <Task finished name='Task-55' coro=<handle() done, defined at accesser\__init__.py:90> exception=LifetimeTimeout('The resolution lifetime expired after 5.155 seconds: Server https://dns.alidns.com/dns-query UDP port 53 answered httpx is not available.; Server https://firefox.cloudflare-dns.com/dns-query UDP port 53 answered httpx is not available.; Server https://185.222.222.222/dns-query UDP port 53 answered httpx is not available.; Server https://45.11.45.11/dns-query UDP port 53 answered httpx is not available.; Server https://dns.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns11.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns10.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns.alidns.com/dns-query UDP port 53 answered httpx is not available.; Server https://firefox.cloudflare-dns.com/dns-query UDP port 53 answered httpx is not available.; Server https://185.222.222.222/dns-query UDP port 53 answered httpx is not available.; Server https://45.11.45.11/dns-query UDP port 53 answered httpx is not available.; Server https://dns.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns11.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns10.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns.alidns.com/dns-query UDP port 53 answered httpx is not available.; Server https://firefox.cloudflare-dns.com/dns-query UDP port 53 answered httpx is not available.; Server https://185.222.222.222/dns-query UDP port 53 answered httpx is not available.; Server https://45.11.45.11/dns-query UDP port 53 answered httpx is not available.; Server https://dns.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns11.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns10.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns.alidns.com/dns-query UDP port 53 answered httpx is not available.; Server https://firefox.cloudflare-dns.com/dns-query UDP port 53 answered httpx is not available.; Server https://185.222.222.222/dns-query UDP port 53 answered httpx is not available.; Server https://45.11.45.11/dns-query UDP port 53 answered httpx is not available.; Server https://dns.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns11.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns10.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns.alidns.com/dns-query UDP port 53 answered httpx is not available.; Server https://firefox.cloudflare-dns.com/dns-query UDP port 53 answered httpx is not available.; Server https://185.222.222.222/dns-query UDP port 53 answered httpx is not available.; Server https://45.11.45.11/dns-query UDP port 53 answered httpx is not available.; Server https://dns.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns11.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns10.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns.alidns.com/dns-query UDP port 53 answered httpx is not available.; Server https://firefox.cloudflare-dns.com/dns-query UDP port 53 answered httpx is not available.; Server https://185.222.222.222/dns-query UDP port 53 answered httpx is not available.; Server https://45.11.45.11/dns-query UDP port 53 answered httpx is not available.; Server https://dns.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns11.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns10.quad9.net/dns-query UDP port 53 answered httpx is not available.')>
Traceback (most recent call last):
  File "accesser\__init__.py", line 102, in handle
  File "accesser\__init__.py", line 161, in DNSquery
  File "dns\asyncresolver.py", line 89, in resolve
  File "dns\resolver.py", line 988, in _compute_timeout
dns.resolver.LifetimeTimeout: The resolution lifetime expired after 5.155 seconds: Server https://dns.alidns.com/dns-query UDP port 53 answered httpx is not available.; Server https://firefox.cloudflare-dns.com/dns-query UDP port 53 answered httpx is not available.; Server https://185.222.222.222/dns-query UDP port 53 answered httpx is not available.; Server https://45.11.45.11/dns-query UDP port 53 answered httpx is not available.; Server https://dns.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns11.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns10.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns.alidns.com/dns-query UDP port 53 answered httpx is not available.; Server https://firefox.cloudflare-dns.com/dns-query UDP port 53 answered httpx is not available.; Server https://185.222.222.222/dns-query UDP port 53 answered httpx is not available.; Server https://45.11.45.11/dns-query UDP port 53 answered httpx is not available.; Server https://dns.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns11.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns10.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns.alidns.com/dns-query UDP port 53 answered httpx is not available.; Server https://firefox.cloudflare-dns.com/dns-query UDP port 53 answered httpx is not available.; Server https://185.222.222.222/dns-query UDP port 53 answered httpx is not available.; Server https://45.11.45.11/dns-query UDP port 53 answered httpx is not available.; Server https://dns.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns11.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns10.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns.alidns.com/dns-query UDP port 53 answered httpx is not available.; Server https://firefox.cloudflare-dns.com/dns-query UDP port 53 answered httpx is not available.; Server https://185.222.222.222/dns-query UDP port 53 answered httpx is not available.; Server https://45.11.45.11/dns-query UDP port 53 answered httpx is not available.; Server https://dns.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns11.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns10.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns.alidns.com/dns-query UDP port 53 answered httpx is not available.; Server https://firefox.cloudflare-dns.com/dns-query UDP port 53 answered httpx is not available.; Server https://185.222.222.222/dns-query UDP port 53 answered httpx is not available.; Server https://45.11.45.11/dns-query UDP port 53 answered httpx is not available.; Server https://dns.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns11.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns10.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns.alidns.com/dns-query UDP port 53 answered httpx is not available.; Server https://firefox.cloudflare-dns.com/dns-query UDP port 53 answered httpx is not available.; Server https://185.222.222.222/dns-query UDP port 53 answered httpx is not available.; Server https://45.11.45.11/dns-query UDP port 53 answered httpx is not available.; Server https://dns.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns11.quad9.net/dns-query UDP port 53 answered httpx is not available.; Server https://dns10.quad9.net/dns-query UDP port 53 answered httpx is not available.

**Comment by URenko** [comment]
那就是没装httpx
```
pip install httpx[http2]
```

**Comment by lxfly2000** [comment]
感谢，已修复

**Comment by lxfly2000** [comment]
今天又出现了这个问题，但是报错变了，HTTPX的所有组件都已安装，希望Reopen这个问题
```
2024-04-20 12:07:07 ERROR    asyncio: Task exception was never retrieved
future: <Task finished name='Task-75' coro=<handle() done, defined at accesser\__init__.py:96> exception=LifetimeTimeout('The resolution lifetime expired after 5.136 seconds: Server https://185.222.222.222/dns-query answered DNS over HTTPS (DOH) was requested but the httpx module is not\n    available.; Server https://45.11.45.11/dns-query answered DNS over HTTPS (DOH) was requested but the httpx module is not\n    available.; Server https://149.112.112.112/dns-query answered DNS over HTTPS (DOH) was requested but the httpx module is not\n    available.; Server https://149.112.112.10/dns-query answered DNS over HTTPS (DOH) was requested but the httpx module is not\n    available.; Server DoT:149.112.112.112@853 answered The DNS operation timed out after 2.000 seconds; Server DoT:149.112.112.10@853 answered The DNS operation timed out after 2.000 seconds; Server DoT:185.222.222.222@853 answered The DNS operation timed out after 0.972 seconds')>
Traceback (most recent call last):
  File "accesser\__init__.py", line 108, in handle
  File "accesser\__init__.py", line 183, in DNSquery
  File "dns\asyncresolver.py", line 89, in resolve
  File "dns\resolver.py", line 1075, in _compute_timeout
dns.resolver.LifetimeTimeout: The resolution lifetime expired after 5.136 seconds: Server https://185.222.222.222/dns-query answered DNS over HTTPS (DOH) was requested but the httpx module is not
    available.; Server https://45.11.45.11/dns-query answered DNS over HTTPS (DOH) was requested but the httpx module is not
    available.; Server https://149.112.112.112/dns-query answered DNS over HTTPS (DOH) was requested but the httpx module is not
    available.; Server https://149.112.112.10/dns-query answered DNS over HTTPS (DOH) was requested but the httpx module is not
    available.; Server DoT:149.112.112.112@853 answered The DNS operation timed out after 2.000 seconds; Server DoT:149.112.112.10@853 answered The DNS operation timed out after 2.000 seconds; Server DoT:185.222.222.222@853 answered The DNS operation timed out after 0.972 seconds
```

**Comment by lxfly2000** [comment]
已经解决了，pip升级一下httpx的版本就好了
