### ISSUE TITLE
nameserver那个选项是否支持`sdns://`链接？

### ISSUE THREAD

**Issue by lxfly2000** [URenko/Accesser#114]
之前用dnscrypt-proxy的时候source的配置是用 https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md 这个链接里的SDNS，现在这个版本我不知道在nameserver那项里是否可以用`sdns://`的链接，有些打不开的网站我想尝试换下DNS
或者如果不支持怎么把它转换成`https://`链接？

**Comment by URenko** [comment]
不支持。
你可以在 https://dnscrypt.info/public-servers 查看它们对应的真实地址。

如果你认为**某几个**网站的DNS有问题，那么应当在`[hosts]`中指定而不是修改DNS服务器，因为默认的这几个DNS服务器都没有污染

**Comment by UjuiUjuMandan** [comment]
是 https://dnscrypt.info/stamps 才能解析出真实地址吧？
