### ISSUE TITLE
能不能搞个docker镜像？

### ISSUE THREAD

**Issue by daiaji** [URenko/Accesser#116]
[OmegaRules_SNI_RST.sorl.zip](https://github.com/URenko/Accesser/files/11041076/OmegaRules_SNI_RST.sorl.zip)
再整个SwitchyOmega的规则订阅。
下级嵌套个GFWLIST就完事了。
说起来Header Editor要用来干嘛？
如果有东西要修复的话也可以在仓库里加个规则订阅。
v2ray的dat也整上吧，下载的话应该能写成脚本。

**Comment by URenko** [comment]
>  能不能搞个docker镜像？

除了python 3.11的不普及外，似乎并没有配置复杂到要用docker。

>  说起来Header Editor要用来干嘛？

过去pixiv登录有点奇怪的地方，需要修改响应体，现在未知。

> 在仓库里加个规则订阅

实际上PAC就能扮演规则订阅的角色，因为一般都可以指定为URL地址，直接指向仓库内的PAC就行（甚至可带CDN）。

不过，直接利用仓库内的PAC确实并不灵活。
我想，使用SwitchyOmega、v2ray的人大部分都有能力自己配置规则？
而且仓库内的规则只是可用网站的很小一部分。
你若愿意在仓库内维护一份这些规则我也是欢迎的。

**Comment by daiaji** [comment]
> 除了python 3.11的不普及外，似乎并没有配置复杂到要用docker。

就是连以激进闻名的Arch都没有3.11啊，这就已经是很大问题了。
最后为了用，我只能在容器跑。
Arch尚且如此，其他的发行版就别说了。
只能说，容器万能论。



> > 
> 
> 实际上PAC就能扮演规则订阅的角色，因为一般都可以指定为URL地址，直接指向仓库内的PAC就行（甚至可带CDN）。
> 
> 不过，直接利用仓库内的PAC确实并不灵活。 我想，使用SwitchyOmega、v2ray的人大部分都有能力自己配置规则？ 而且仓库内的规则只是可用网站的很小一部分。 你若愿意在仓库内维护一份这些规则我也是欢迎的。

```
[SwitchyOmega Conditions]
; Require: SwitchyOmega >= 2.3.2
; Date: 2023/3/22
; Usage: https://github.com/FelisCatus/SwitchyOmega/wiki/RuleListUsage

*.apkmirror.com
*.appledaily.com
*.archiveofourown.org
*.artstation.com
*.bbc.com
*.disqus.com
*.dmc.nico
*.dropbox.com
*.dropboxapi.com
*.dropbox-dns.com
*.dw.com
*.e-hentai.org
*.epochtimes.com
*.euronews.com
*.exhentai.org
*.ftchinese.com
*.github.com
*.githubassets.com
*.githubusercontent.com
*.imgur.com
*.instagram.com
*.i.pximg.net
*.kobo.com
*.medium.com
*.mega.nz
*.nicovideo.jp
*.nyaa.si
*.nytimes.com
*.phncdn.com
*.pinterest.com
*.pixiv.net
*.pornhub.com
*.quora.com
*.redd.it
*.reddit.com
*.redditmedia.com
*.redditstatic.com
*.startpage.com
*.steamcommunity.com
*.theepochtimes.com
*.thetvdb.com
*.tumblr.com
*.tumblr.co
*.uptodown.com
*.vimeo.com
*.wenxuecity.com
*.wikipedia.org
```
SwitchyOmega规则超简单。

也许和PAC一起能用脚本生成？

**Comment by URenko** [comment]
> 就是连以激进闻名的Arch都没有3.11啊，这就已经是很大问题了。

使用pyenv可用方便地管理python版本，对于两边都是新手的人来说或许pyenv更易使用？

而从另一方面来讲，就是连以稳定闻名（不考虑某已死亡的发行版）的Debian也将在几个月后默认3.11（bookworm成为stable）
遗憾的是Ubuntu没赶上

总之，你若愿意维护一份docker镜像我也是欢迎的

**Comment by daiaji** [comment]
> 使用pyenv可用方便地管理python版本，对于两边都是新手的人来说或许pyenv更易使用？

docker更通用。

**Comment by daiaji** [comment]
@URenko 这就是要改请求头了？
![image](https://user-images.githubusercontent.com/25875791/227771931-1c01c2c0-4599-48af-8e79-870c2da31c6b.png)

**Comment by URenko** [comment]
建议查看Accesser的日志以了解发生了什么。
另外NS_BINDING_ABORTED并不一定意味着错误，可能只是连接被你打断了（如刷新页面）

> 根证书缓存在哪里

既然你用docker，我猜测里面是Linux，存在工作目录的`CERT/root.*`
也可通过 http://localhost:7654/CERT/root.crt root.key 获取

**Comment by URenko** [comment]
see also 5e96cc59ee9b7bdbcdc056be70146fa2ba03238f

**Comment by lxsq** [comment]
> > 使用pyenv可用方便地管理python版本，对于两边都是新手的人来说或许pyenv更易使用？
> 
> docker更通用。 我先把docker的支持整上去吧。 我在项目根目录下创建个文件夹吧。 然后放上需要改动的配置文件和Dockerfile。 但你需要连接hub,然后让hub自己编译镜像。

请问Dockerfile整好了吗

**Comment by daiaji** [comment]
> > > 使用pyenv可用方便地管理python版本，对于两边都是新手的人来说或许pyenv更易使用？
> > 
> > 
> > docker更通用。 我先把docker的支持整上去吧。 我在项目根目录下创建个文件夹吧。 然后放上需要改动的配置文件和Dockerfile。 但你需要连接hub,然后让hub自己编译镜像。
> 
> 请问Dockerfile整好了吗

我用phantomsocks，py和我相性挺差的。

**Comment by lxsq** [comment]
突然又想起来这事，加上了https://github.com/URenko/Accesser/pull/207
