### ISSUE TITLE
网页打开速度好像比旧版本慢了

### ISSUE THREAD

**Issue by lxfly2000** [URenko/Accesser#117]
比如访问GitHub，旧版基本上秒开，换0.8.0后经常等好久，有时候图片都显示不全

**Comment by URenko** [comment]
虽然似乎有这种感觉，但我现在复现不出
2f25a05c4cc30723b4ac45f1071af5b460a0da59 可能对图片显示不全有帮助。

可以尝试修改这里的数字，但其实是与旧版同样的值
https://github.com/URenko/Accesser/blob/2f25a05c4cc30723b4ac45f1071af5b460a0da59/accesser/__init__.py#L87

**Comment by URenko** [comment]
stale
