### ISSUE TITLE
2023-03-31 21:33:43 ERROR    asyncio: Task exception was never retrieved

### ISSUE THREAD

**Issue by goehls** [URenko/Accesser#118]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/77818535/229134344-89b63c53-7099-4d17-ba80-1ad5817a86cf.png">

**Comment by URenko** [comment]
正如日志所提示的：`httpx is not available`

所以要么安装httpx：
```
pip install httpx[http2]
```
要么把默认的这些DoH服务器（需要httpx）地址改为别的

**Comment by goehls** [comment]
<img width="1395" alt="image" src="https://user-images.githubusercontent.com/77818535/230767180-ea7a09a7-ff45-4683-a8e3-4b9e287f74a0.png">

**Comment by goehls** [comment]
安装时如果带上[doh]无法正常安装：
<img width="403" alt="image" src="https://user-images.githubusercontent.com/77818535/230767242-da50f676-d89f-4069-b299-276ac37544bb.png">

**Comment by URenko** [comment]
因为你使用了zsh，`[`、`]`会被视为特殊字符，所以你需要
```
pip3 install -U 'accesser[doh]'
```
或
```
pip3 install -U accesser\[doh\]
```

对于前一个问题，暂不清楚，你可能需要确认下是否已经导入证书，或是需要`pip3 uninstall accesser`卸载再重新安装

**Comment by goehls** [comment]
我使用的是mac系统。我看到这里的文档，并没有说明要安装哪些证书，只是看到windows系统会有证书安装。不知道要导入哪些证书呢

**Comment by URenko** [comment]
运行accesser后从 http://localhost:7654/CERT/root.crt 下载根证书，然后导入系统并**信任**，可以参考[Fiddler的说明](https://docs.telerik.com/fiddler-everywhere/knowledge-base/how-to-install-fiddler-root-certificate-on-mac-os)或自行搜索。

如果是使用Firefox浏览器，可以直接在浏览器中导入，具体自行搜索
