### ISSUE TITLE
WIN上一些问题

### ISSUE THREAD

**Issue by miaomiaosoft** [URenko/Accesser#12]
WIN7 X64
运行6.0版几个命令行窗口闪过就没然后了
怀疑证书没有正常生成的缘故，目录下也没有CERT文件夹，后下载5.0运行后复制生成的CERT文件夹和START.BAT到6.0倒能正常运行了

另外不知是不是内置的DOH不支持IPV6解析，有些网站无法连接，比如FACEBOOK和DROPBOX，因IPV4的地址基本都进黑洞了，自行添加HOSTS后倒是能访问：
facebook.com = 2a03:2880:f102:183:face:b00c:0:25de
www.facebook.com = 2a03:2880:f102:183:face:b00c:0:25de
static.xx.fbcdn.net = 2a03:2880:f002:215:face:b00c:0:3
staticxx.facebook.com = 2a03:2880:f002:215:face:b00c:0:3
fbsbx.com = 2a03:2880:f102:183:face:b00c:0:25de
dropbox.com = 2620:100:6040:1::a27d:f801
www.dropbox.com = 2620:100:6032:1::a27d:5201
photos-1.dropbox.com = 162.125.82.5

所以希望能增加选项使用自己本地的DNS，因为用的dnsforwarder，支持通配符使用HOSTS也比较方便

bbc.co.uk 生成的证书域名为co.uk导致证书错误
cn.reuters.com cn.nytimes.com cn.wsj.com 这类网站可能需要特别处理，共同点似乎都用的cloudfront

**Comment by URenko** [comment]
@miaomiaosoft 
1. 你6.0版是用那个releases里的exe吗，如果是那个的话从6.0版开始不再默认使用终端窗口，改用webui，所以“几个命令行窗口闪过就没然后了”是正常的，不过应该会打开一个网页，然后CERT文件夹也不会出现，因为都在缓存文件夹里
2. 暂时缺少IPv6测试环境，所以可能过段时间后考虑这些网站
3. 本地DNS的选项将考虑加入
4. 证书自动生成的错误将会修复
感谢报告

**Comment by miaomiaosoft** [comment]
补充：是那个EXE,窗口闪过后是打开了http://localhost:7654/，不过是无法访问的，查看进程也没发现python的

感谢回复

**Comment by URenko** [comment]
复制CERT文件夹和start.bat后是直接运行Accesser.exe吗，有无导入证书的提示（参考https://urenko.github.io/Accesser/
正常运行后，移去CERT文件夹和start.bat是否能正常运行？[http://localhost:7654/](http://localhost:7654/)是否能打开？

**Comment by miaomiaosoft** [comment]
复制后是直接运行start.bat，停留在命令行窗口，功能正常，没见到有证书导入提示

6.0的文件我是用7Z从Accesser.exe解压出来的，我不知道它自解压到哪了
移去CERT文件夹和START.BAT那只能自己命令行运行了：
F:\Accesser>python\python.exe accesser.py
Accesser v0.6.0  Copyright (C) 2018-2019  URenko
My
CertUtil: -exportPFX 失败: 0x80090011 (-2146893807)
CertUtil: 找不到对象。
CertUtil: -importPFX 失败: 0x80070057 (WIN32: 87)
CertUtil: 参数错误。
My
CertUtil: -delstore 命令成功完成。

F:\Accesser>python\python.exe accesser.py -rr
Accesser v0.6.0  Copyright (C) 2018-2019  URenko
My
CertUtil: -exportPFX 失败: 0x80090011 (-2146893807)
CertUtil: 找不到对象。
CertUtil: -importPFX 失败: 0x80070057 (WIN32: 87)
CertUtil: 参数错误。
My
CertUtil: -delstore 命令成功完成。

都是新建CERT空文件夹后就闪退了

系统证书只在 受信任的根证书 找到accesser的
![qq 20190217144639](https://user-images.githubusercontent.com/4084875/52909390-db8ce900-32c2-11e9-88ef-e685c35f64f9.jpg)

**Comment by URenko** [comment]
exportPFX找不到对象是正常的，importPFX的参数错误我这里无法复现
我在导入证书前加入了暂停，从[这里](https://send.firefox.com/download/99e71b3f1b/#7623KU2UlD3cIQ3kDQDwkg)下载覆盖同名文件既可，清空CERT文件夹后，命令行启动后出现`请按任意键继续. . .`时你可以检查下CERT文件夹下有无**root.pfx**文件，如果有，可以尝试`CertUtil -f -user -p "" -importPFX My CERT\root.pfx`命令进行手动导入，看看问题是否复现，如果复现，可以上传(通过[send.firefox.com](https://send.firefox.com)或打包后通过github)**root.pfx**我看一下。
另外，-rr参数在6.0版已被取消，所以与无参数效果相同，证书将导入**受信任的根证书**和**个人**(6.0版之后)区域

**Comment by miaomiaosoft** [comment]
按照操作后个人和受信任的根都有了Accesser证书
再运行Accesser.exe正常了

谢谢！

**Comment by URenko** [comment]
``CertUtil -f -user -p "" -importPFX My CERT\root.pfx``没有出错？

**Comment by miaomiaosoft** [comment]
命令行进入到证书目录
再
CertUtil -f -user -p "" -importPFX root.pfx
弹出导入证书窗口
确定

没有出错

**Comment by linsui** [comment]
我不确定是不是同一个问题，win10 上运行之后自解压，然后就没有其他动作了，网页显示连接被重置。请问有什么解决办法吗？

**Comment by URenko** [comment]
@linsui 目前已知的可能原因是同时使用VPN。此外这个问题里表现出证书导入存在问题，可先检查下Pyhton进程是否存在，如果没有可按照这个问题进行分析。下一版本会对证书导入问题进行改进。

**Comment by linsui** [comment]
我猜我找到原因了，7654 端口和 I2P 冲突。请问有什么办法改端口吗？另外希望加一些错误信息

**Comment by URenko** [comment]
手动解压后运行应该是有调试信息的（自解压会自动删除）

**Comment by linsui** [comment]
@URenko 谢谢，我刚刚发现这一点。
