### ISSUE TITLE
关于Cloudflare

### ISSUE THREAD

**Issue by ChocolaVanilla0305** [URenko/Accesser#122]
以Rutracker为例子
根据「如何适配站点」的内容
得到
IPv6: "2a03:2880:f127:283:face:b00c:0:25de"
Ipv4: "69.162.134.178"
放入ip138得到毫无关系的归属，遭到了DNS污染
放入"dns.google"得到
{
  "Status": 0 /* NOERROR */,
  "TC": false,
  "RD": true,
  "RA": true,
  "AD": false,
  "CD": false,
  "Question": [
    {
      "name": "rutracker.org.",
      "type": 1 /* A */
    }
  ],
  "Answer": [
    {
      "name": "rutracker.org.",
      "type": 1 /* A */,
      "TTL": 300,
      "data": "104.21.72.173"
    },
    {
      "name": "rutracker.org.",
      "type": 1 /* A */,
      "TTL": 300,
      "data": "172.67.187.38"
    }
  ],
  "Comment": "Response from 108.162.193.78."
}
三个IP都可以ping通
使用curl测试三个ip都出现
"failed to receive handshake, SSL/TLS connection failed"错误
配置Accesser后显示
"ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:992)"
于是在[alter_hostname]填入
"rutracker.org" = "cloudflare.com"
再次访问网站得到控制台输出
"say: CONNECT rutracker.org:443 HTTP/1.1"
"DNS: rutracker.org -> 2606:4700:3033::6815:48ad"
"server_hostname='cloudflare.com'"
"cert.get('subjectAltName', ())=(('DNS', 'secondary.cloudflare.com'), ('DNS', 'ns.cloudflare.com'), ('DNS', '*.ns.cloudflare.com'), ('DNS', '*.secondary.cloudflare.com'), ('DNS', 'cloudflare.com'))"
网站显示
"403 Forbidden"
"cloudflare"
想请教一下怎么办

**Comment by URenko** [comment]
alter_hostname 设置了`server_name`，cloudflare等CDN一般通过这一值判断你要访问的是什么网站，填`'cloudflare.com'`cloudflare就以为你要访问的是cloudflare.com网站本身了。

从实践上来讲，rutracker使用的cloudflare CDN plan不支持这种操作。
