### ISSUE TITLE
请求支持Discord

### ISSUE THREAD

**Issue by charles-cty** [URenko/Accesser#123]
请求支持discord.com的访问，我尝试过根据Wiki适配这个站点，但discord.com使用了Cloudflare的服务，不知道该怎么做
Discord是相当知名的社区之一，比较常用，麻烦帮忙支持一下discord.com的访问，感激不尽！

**Comment by URenko** [comment]
Cloudflare CDN应考虑ECH或http3，基本上不支持域前置。

关联：#51

**Comment by URenko** [comment]
已于 [v0.8.2](https://github.com/URenko/Accesser/releases/tag/v0.8.2) 适配
