### ISSUE TITLE
关于通配符的一个问题

### ISSUE THREAD

**Issue by Kenxu2022** [URenko/Accesser#127]
现需对谷歌系的网址设置server name，但在config.toml文件中似乎无法通过通配符设置```*.gstatic.com```等网址的server name，只能一个一个设置，请问应该怎么办？

**Comment by URenko** [comment]
让alter_hostname支持通配符的话，发送server name这边问题不大，麻烦点的是证书匹配这边，如果不是只用`loosely_dnsname_match`，就要重新写下`ssl._dnsname_match`

**Comment by Kenxu2022** [comment]
那还有劳大佬适配了，一个一个添加域名真的太累了😂
不过我一直都是关闭证书域名校验的，不考虑这玩意的情况下适配起来会不会简单一些？

**Comment by Kenxu2022** [comment]
大佬神速，已经用上了，再次感谢🥰
