### ISSUE TITLE
`http://` forward support

### ISSUE THREAD

**Issue by NewUserHa** [URenko/Accesser#128]
which can avoid in-application proxy changing to browser `http://` sites.

**Comment by URenko** [comment]
You mean provide a proxy in Accesser to forward http-only sites?
They should not be passed into Accesser and routing  can be easily done via e.g. PAC.

**Comment by NewUserHa** [comment]
yes.
but some probably can't use PAC file, I don't have an example though.

**Comment by URenko** [comment]
not planned
