### ISSUE TITLE
e站表站IP疑似被封锁，无法直连，可通过增加配置文件IP直连

### ISSUE THREAD

**Issue by Loli0721** [URenko/Accesser#129]
https://ehwiki.org/wiki/IPs
可替换IP为
37.48.89.16
81.171.10.55
178.162.139.18
178.162.147.246
即在配置文件末尾增加"e-hentai.org" = "上面四个任意一个IP"
目前暂时不知道IP被封锁的原因
里站暂时不受影响

**Comment by URenko** [comment]
很可能和最近流行的移除通过触发墙来封锁任意 cloudflare IP 有关

已失效
c.f. https://nicebowl.fun/11

**Comment by URenko** [comment]
已恢复直连
