### ISSUE TITLE
安卓使用无法访问duckduckgo

### ISSUE THREAD

**Issue by Xihihhh** [URenko/Accesser#131]
无root，duckduckgo应该只是DNS污染，但是只要开启accesser就一直是重置连接，关掉accesser再开启Virtual Hosts(VPN)就没问题。尝试过删掉pac文件里的duckduckgo，没用

**Comment by URenko** [comment]
- 其他网站呢
- 贴日志
- DNS污染不该用DNS污染的专用解决方案吗

**Comment by Xihihhh** [comment]
额，只要把duckduckgo加进pac domins里就行了。。。

**Comment by louiesun** [comment]
> 无root，duckduckgo应该只是DNS污染，但是只要开启accesser就一直是重置连接，关掉accesser再开启Virtual Hosts(VPN)就没问题。尝试过删掉pac文件里的duckduckgo，没用

一个无关的事：duckduckgo自己被gfw封了为什么还在执行审查？（你搜64和维尼的结果跟翻墙结果不一样，改地区也没用），那干嘛不用cnbing
