### ISSUE TITLE
从Scoop中下载的python，修改Accesser配置文件无效

### ISSUE THREAD

**Issue by ListenV** [URenko/Accesser#140]
系统环境：Win11
Accesser：v0.8.3

从Scoop中下载的python3.11，使用自带PIP安装Accesser后，在Accesser目录中修改config.toml，重启程序后依然无效

![image](https://github.com/URenko/Accesser/assets/45219522/a9cb671d-0b19-4722-bd1c-43475635215f)

**Comment by URenko** [comment]
> 编辑**工作目录**下的config.toml

**Comment by ListenV** [comment]
下载exe就可以了，或者直接运行源码

但是日志有很多错误
