### ISSUE TITLE
github.io: sslv3 alert certificate unknown (_ssl.c:1000)

### ISSUE THREAD

**Issue by Xihihhh** [URenko/Accesser#151]
开启 Accesser 访问 [https://github.io](https://github.io) 时，
Accesser: ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1000)
浏览器: NET::ERR_CERT_COMMON_NAME_INVALID，此服务器无法证明它是 **github.io**；它的安全证书来自 **github.io.github.io**。这可能是由错误配置或者有攻击者截获你的连接而导致的。
不是网站的问题，不开的时侯正常跳转到 [https://pages.github.com/?(null)](https://pages.github.com/?(null))

**Comment by jonm58** [comment]
![image](https://github.com/URenko/Accesser/assets/73036321/59400251-eaec-48ed-8845-e0e153c5a87f)
你的sni name?

**Comment by jonm58** [comment]
也许是https://github.io -> http://github.io.github.io -> https://pages.github.com/?(null) -> https://github.com/?(null)

**Comment by Xihihhh** [comment]
> ![image](https://user-images.githubusercontent.com/73036321/277997741-59400251-eaec-48ed-8845-e0e153c5a87f.png) 你的sni name?

空

**Comment by Xihihhh** [comment]
> > 只有github.io有，*.github.io没问题
> 
> 就github.io.github.io只有http
> 
> *.github.io和github.io有https和http
> 
> 就像你不能用*.google.com证书给*.l.google.com一样

不太理解，github.io.github.io也有https
![屏幕截图 2023-10-26 114852](https://github.com/URenko/Accesser/assets/111831296/96298cc2-35b2-4efc-88aa-e5cd0f63d767)

**Comment by URenko** [comment]
首先并没有跳转 github.io.github.io。
根据日志，Accesser 错误地使用对应于 github.io.github.io 的证书与浏览器建立连接。

原因在于 github.io 本身[被认为是一个 TLD](https://github.com/barseghyanartur/tld/blob/e7d6c0b62adaf7140e9a2232898844290e9610a0/src/tld/res/effective_tld_names.dat.txt#L12196)，引起了错乱。
