### ISSUE TITLE
未能将hosts字段也用于解析DOH的IP地址

### ISSUE THREAD

**Issue by Scarecrow-ai** [URenko/Accesser#156]
在hosts下添加了
"dns.alidns.com" = "223.5.5.5"
但在nameserver中使用
  "https://223.5.5.5/dns-query"正常解析
  "https://dns.alidns.com/dns-query"解析超时。

其他DNS也有类似的情况

**Comment by jonm58** [comment]
> dns.alidns.com/dns-query"解析超时。

试一试:"dns.alidns.com" = "223.6.6.6"

**Comment by Scarecrow-ai** [comment]
> 试一试:"dns.alidns.com" = "223.6.6.6"

同样解析超时。

**Comment by URenko** [comment]
确认为上游 dnspython 的 bug，已提交 pr
https://github.com/rthalley/dnspython/pull/1018
