### ISSUE TITLE
修改PAC添加网站

### ISSUE THREAD

**Issue by P-256** [URenko/Accesser#16]
请问如何修改pac来添加网站？前几次修改都失败了，RST的还是被RST

**Comment by URenko** [comment]
修改前要解压，以后要通过命令行启动，或者用老版里的start.bat（这里还没设计好）
domains里是匹配域名最后两个，shexps是通配符匹配，修改完后要重启程序。
可以在改完后访问中文维基以验证PAC是否格式正确（被浏览器正确识别）

**Comment by P-256** [comment]
> 修改前要解压，以后要通过命令行启动，或者用老版里的start.bat（这里还没设计好）
> domains里是匹配域名最后两个，shexps是通配符匹配，修改完后要重启程序。
> 可以在改完后访问中文维基以验证PAC是否格式正确（被浏览器正确识别）

如何通过命令行启动呢

**Comment by URenko** [comment]
最简单的方法就是在解压后的目录下运行此文件（解压后）
[start.zip](https://github.com/URenko/Accesser/files/2965024/start.zip)

**Comment by P-256** [comment]
> 最简单的方法就是在解压后的目录下运行此文件（解压后）
> [start.zip](https://github.com/URenko/Accesser/files/2965024/start.zip)

不行啊，改完之后在启动DOH这一步就没有提示了，反倒是之前能用的也不行了

**Comment by URenko** [comment]
@P-256 启动DoH视网络状况需要的时间会有较大差异，最长可能要十几秒，我觉得可能是这个问题。

**Comment by P-256** [comment]
> @P-256 启动DoH视网络状况需要的时间会有较大差异，最长可能要十几秒，我觉得可能是这个问题。

but之前能用的也不行了，加了bbc.com之后就不行了。
domains，shexps都按照格式编写都不行，甚至单独一个域名的也不行（但是加了个ug.wikipedia.org又OK,......）

**Comment by URenko** [comment]
我觉得就是PAC格式有问题，能发下出问题的PAC文件吗 @P-256
