### ISSUE TITLE
[功能请求] 允许特定网站不校验证书

### ISSUE THREAD

**Issue by PYUDNG** [URenko/Accesser#161]
如题，关闭证书校验不安全，但是有些网站确实不能通过本地证书校验（不发送SNI，服务器允许访问，但返回的默认证书所在域名也被屏蔽，如果使此用证书域名作为`alter_hostname`则无法访问）。对此，有如下功能请求：
1. 是否可以支持对特定网站关闭证书校验？
2. 是否可以支持对特定网站分开设置<code>**用于发送**的SNI字段</code>和<code>**用于证书校验**的SNI字段</code>？

即黑名单制地允许网站绕过证书校验，当不安全地访问这些网站时，确保其他支持通过证书校验网站依然是受到证书校验的保护的。

**Comment by URenko** [comment]
有无例子？虽然早知道有这一缺陷，但六年了也没见着一个

**Comment by jonm58** [comment]
bandcamp.com?

**Comment by PYUDNG** [comment]
我这里`singlelogin.se`无SNI访问时偶尔返回的证书是`1lib.fr`的，然而alter_hostname设置为`1lib.fr`访问singlelogin.se就会RST

**Comment by PYUDNG** [comment]
另外`singlelogin.re`无SNI时可以访问但是不能通过证书校验，所以想要通过单独允许此域名不进行证书校验来允许访问。

**Comment by Xihihhh** [comment]
> 我这里`singlelogin.se`无SNI访问时偶尔返回的证书是`1lib.fr`的，然而alter_hostname设置为`1lib.fr`访问singlelogin.se就会RST

我这一直返回`singlelogin.re`，但`singlelogin.re`和`1lib.fr`都会RST，所以当时PR没加上

> 另外`singlelogin.re`无SNI时可以访问但是不能通过证书校验，所以想要通过单独允许此域名不进行证书校验来允许访问。

我这一直都能过证书校验

**Comment by PYUDNG** [comment]
> > 我这里`singlelogin.se`无SNI访问时偶尔返回的证书是`1lib.fr`的，然而alter_hostname设置为`1lib.fr`访问singlelogin.se就会RST
> 
> 我这一直返回`singlelogin.re`，但`singlelogin.re`和`1lib.fr`都会RST，所以当时PR没加上
> 
> > 另外`singlelogin.re`无SNI时可以访问但是不能通过证书校验，所以想要通过单独允许此域名不进行证书校验来允许访问。
> 
> 我这一直都能过证书校验

![截屏2024-03-01 下午1 08 07](https://github.com/URenko/Accesser/assets/63054558/3f519245-b09e-42b2-9d38-f6fef06ec73c)

我这里情况是这样的

**Comment by URenko** [comment]
@Xihihhh 看起来你之前在 #155 提到的 singlelogin.re 需要指定 IP 与此有关？现在似乎可以移除了

**Comment by PYUDNG** [comment]
已测，我这里没有问题。
期待release！

**Comment by Xihihhh** [comment]
之前好像过不了证书校验就无法访问，怎么现在未过也能访问了？

**Comment by URenko** [comment]
> 之前好像过不了证书校验就无法访问，怎么现在未过也能访问了？

应该在 8c73c3c97257f5f52d62cca81f6305b740712723 修复
