### ISSUE TITLE
命令行可以运行但用PyInstaller打包后运行提示“httpx is not available”

### ISSUE THREAD

**Issue by lxfly2000** [URenko/Accesser#164]
https://github.com/URenko/Accesser/issues/113#issuecomment-2067543685
刚刚遇到这个问题，解决以后用PyInstaller打包后的程序运行发现还是这样，但是命令行就没有问题

**Comment by URenko** [comment]
无法复现。
`pip install -U dnspython[doh]` 以及对 pyinstaller 使用 `--clean` 试试

**Comment by lxfly2000** [comment]
已解决，加上--clean就好了
