### ISSUE TITLE
一个更加简单的使用域前置的方法

### ISSUE THREAD

**Issue by louiesun** [URenko/Accesser#169]
只需要一个chromium核浏览器
使用命令行。
第一个参数会导致用IP作为sni，第二个会忽略证书错误（理论上有安全风险）。
```bash
chrome --host-rules="MAP libgen.rs 193.218.118.42,MAP www.torproject.org 116.202.120.165" --ignore-certificate-errors
```
当然，cloudflare是不支持域前置的。但是可以用QUIC。

**Comment by Xihihhh** [comment]
测得谷歌无证书错误。

**Comment by URenko** [comment]
Firefox Lives Matter!
https://zh.wikipedia.org/wiki/Help:如何访问维基百科/Firefox浏览器补丁
