### ISSUE TITLE
适配 docker.com 时出现的问题

### ISSUE THREAD

**Issue by aimagic** [URenko/Accesser#170]
我按照文档配置了 `[alter_hostname]`, 但 `curl https://docker.com -x http://localhost:7654 -v --insecure` 时出现了如下响应, 请问如何解决?

```html
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
```

**Comment by URenko** [comment]
cloudflare 禁止，因此 Accesser 不可行。
最好是考虑 HTTP/3 或是 ECH。
