### ISSUE TITLE
使用pixiv时突然出现的问题

### ISSUE THREAD

**Issue by Lingstarcn** [URenko/Accesser#171]
因为是纯小白，所以对该问题一窍不通==
![屏幕截图 2024-06-13 130446](https://github.com/URenko/Accesser/assets/98258315/36e380ba-bab1-4aad-b702-8871198ff038)
之前可以正常使用，是最近突然出现的问题。
当访问时，网站并未返回任何数据
![屏幕截图 2024-06-13 131340](https://github.com/URenko/Accesser/assets/98258315/fc3d31bd-9da8-432f-9837-c50371502225)

**Comment by jonm58** [comment]
可以在cmd里ping www.pixiv.net吗?

**Comment by Xihihhh** [comment]
> 可以在cmd里ping www.pixiv.net吗?

小白大概不会自己给 cmd 设一个 EDNS，ping 出来是污染的。

**Comment by Lingstarcn** [comment]
![屏幕截图 2024-06-13 224817](https://github.com/URenko/Accesser/assets/98258315/bc9581b4-a9b5-40b8-be13-c0d102b77d4f)

十分感谢大佬的回复，我在没有进行任何修改的情况下很奇怪的现在又可以正常使用pixiv了，不过按网上教程ping出来还是像这样==
能麻烦您教我ENDS的设置又是怎么一回事吗？我不太清楚发生这个问题的原因。
