### ISSUE TITLE
请问['upos-sz-mirror08c.bilivideo.com'] don't march either of是什么错误

### ISSUE THREAD

**Issue by conanlm** [URenko/Accesser#177]
公司把许多视频网站封了，我想上b站
添加了b站相关地址，页面能加载，但是视频会报这个错，是什么问题啊
```
                    WARNING  [ 6324] ['upos-sz-mirror08c.bilivideo.com'] don't march either of          __init__.py:148                              subjectAltName: (('DNS', 'n.cdnhwc3.com'), ('DNS',                                                                      'appgallery.huawei.com'), ('DNS', '*.n.cdnhwc3.com'), ('DNS',                                                           '*.cntv.myhwcdn.cn'), ('DNS', '*.cdnhwc3.com'), ('DNS', '*.hicloud.com'),                                               ('DNS', '*.dt.hicloud.com'), ('DNS', '*.data.hicloud.com'), ('DNS',                                                     '*.data.dbankcloud.cn'), ('DNS', '*.data.dbankcloud.com'), ('DNS',                                                      '*.dt.dbankcloud.com'), ('DNS', '*.dt.dbankcloud.cn'), ('DNS',                                                          '*.dbankcloud.cn'), ('DNS', '*.dbankcloud.com'), ('DNS',                                                                '*.huawei.com.cn'), ('DNS', '*.cloud.huawei.com'), ('DNS',                                                              '*.cloud.huawei.com.cn'), ('DNS', '*.hispace.hicloud.com'), ('DNS',                                                     '*.hispace.dbankcloud.cn'), ('DNS', '*.hispace.dbankcloud.com'), ('DNS',                                                '*.push.dbankcloud.com'), ('DNS', '*.push.hicloud.com'), ('DNS',                                                        '*.push.dbankcloud.cn'), ('DNS', '*.ads.huawei.com'), ('DNS',                                                           '*.op.cloud.huawei.com'), ('DNS', '*.ads.huawei.com.cn'), ('DNS',                                                       '*.platform.hicloud.com'), ('DNS', '*.platform.dbankcloud.com'), ('DNS',                                                '*.platform.dbankcloud.cn'), ('DNS', '*.cloud.hicloud.com'), ('DNS',                                                    '*.cloud.dbankcloud.com'), ('DNS', '*.cloud.dbankcloud.cn'), ('DNS',                                                    '*.wallet.dbankcloud.com'), ('DNS', '*.iap.dbankcloud.com'), ('DNS',                                                    '*.dianping.com'), ('DNS', '*.dpfile.com'), ('DNS', '*.meituan.net'),                                                   ('DNS', '*.zservey.net')), subject: ((('countryName', 'CN'),),                                                          (('stateOrProvinceName', 'Jiangsu'),), (('localityName', 'Nanjing'),),                                                  (('organizationName', 'Huawei Software Technologies Co., Ltd.'),),                                                      (('commonName', 'n.cdnhwc3.com'),)).     
```

**Comment by jonm58** [comment]
![RyoMoffster](https://cdn.discordapp.com/emojis/1059648830053818378.webp?&name=RyoMoffster)
你是怎么加进去的?

**Comment by Xihihhh** [comment]
域名多，干脆直接关闭证书校验：

修改`config.toml`中 check_hostname 的值为 false，即 check_hostname = false

**Comment by conanlm** [comment]
> ![RyoMoffster](https://camo.githubusercontent.com/c253c0946e719e9a553eeaa131a958520ab7eb71f2af0fecb0f030b1439f0478/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f313035393634383833303035333831383337382e776562703f266e616d653d52796f4d6f666673746572) 你是怎么加进去的?

我是在PAC文件 var domains里面添加
  "bilibili.com": 1,
  "hdslb.com": 1,
  "i1.hdslb.com": 1,
  "bilivideo.com": 1,

**Comment by Xihihhh** [comment]
> "hdslb.com": 1,

加了一级域名，其子域名也会走 Accesser，不必再加 i1.hdslb.com

**Comment by jonm58** [comment]
你没把这些放进去
```
i0.hdslb.com
i2.hdslb.com
s1.hdslb.com
s2.hdslb.com
s3.hdslb.com
```

**Comment by conanlm** [comment]
> > "hdslb.com": 1,
> 
> 加了一级域名，其子域名也会走 Accesser，不必再加 i1.hdslb.com

开始我是只加了hdslb.com，还是访问不了，所以尝试加了 i1.hdslb.com

**Comment by Xihihhh** [comment]
> > > "hdslb.com": 1,
> > 
> > 
> > 加了一级域名，其子域名也会走 Accesser，不必再加 i1.hdslb.com
> 
> 开始我是只加了hdslb.com，还是访问不了，所以尝试加了 i1.hdslb.com

访问不了是因为证书校验问题，关闭校验就行了

**Comment by conanlm** [comment]
> > > > "hdslb.com": 1,
> > > 
> > > 
> > > 加了一级域名，其子域名也会走 Accesser，不必再加 i1.hdslb.com
> > 
> > 
> > 开始我是只加了hdslb.com，还是访问不了，所以尝试加了 i1.hdslb.com
> 
> 访问不了是因为证书校验问题，关闭校验就行了

这是我fork https://github.com/conanlm/Accesser 的地址
还是不行，b站页面能打开了，但是hdslb.com地址还是加载不了
![图片_lanxin_20240716104856](https://github.com/user-attachments/assets/3c407402-c688-4aca-9c82-a58264ea89ae)

**Comment by jonm58** [comment]
> > > > > "hdslb.com": 1,
> > > > 
> > > > 
> > > > 加了一级域名，其子域名也会走 Accesser，不必再加 i1.hdslb.com
> > > 
> > > 
> > > 开始我是只加了hdslb.com，还是访问不了，所以尝试加了 i1.hdslb.com
> > 
> > 
> > 访问不了是因为证书校验问题，关闭校验就行了
> 
> 这是我fork https://github.com/conanlm/Accesser 的地址 还是不行，b站页面能打开了，但是hdslb.com地址还是加载不了 ![图片_lanxin_20240716104856](https://private-user-images.githubusercontent.com/2777986/348922657-3c407402-c688-4aca-9c82-a58264ea89ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwOTkxMTYsIm5iZiI6MTcyMTA5ODgxNiwicGF0aCI6Ii8yNzc3OTg2LzM0ODkyMjY1Ny0zYzQwNzQwMi1jNjg4LTRhY2EtOWM4Mi1hNTgyNjRlYTg5YWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTZUMDMwMDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDZkOTM0NjcxMWVhYjAzY2ZhMjIwMjZmNzZhNTM5M2U1MGY3YWY0YTQ3YzlhZTcwNGRkMWU5NTUwNjhiM2NiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rbvoij4zyhANp3Pl-rlVJvZ4GpC8hMIbb-9TNJnDBKs)

修改DNS为114.114.114.114之类的

**Comment by conanlm** [comment]
> > > > > > "hdslb.com": 1,
> > > > > 
> > > > > 
> > > > > 加了一级域名，其子域名也会走 Accesser，不必再加 i1.hdslb.com
> > > > 
> > > > 
> > > > 开始我是只加了hdslb.com，还是访问不了，所以尝试加了 i1.hdslb.com
> > > 
> > > 
> > > 访问不了是因为证书校验问题，关闭校验就行了
> > 
> > 
> > 这是我fork https://github.com/conanlm/Accesser 的地址 还是不行，b站页面能打开了，但是hdslb.com地址还是加载不了 ![图片_lanxin_20240716104856](https://private-user-images.githubusercontent.com/2777986/348922657-3c407402-c688-4aca-9c82-a58264ea89ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwOTkxMTYsIm5iZiI6MTcyMTA5ODgxNiwicGF0aCI6Ii8yNzc3OTg2LzM0ODkyMjY1Ny0zYzQwNzQwMi1jNjg4LTRhY2EtOWM4Mi1hNTgyNjRlYTg5YWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTZUMDMwMDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDZkOTM0NjcxMWVhYjAzY2ZhMjIwMjZmNzZhNTM5M2U1MGY3YWY0YTQ3YzlhZTcwNGRkMWU5NTUwNjhiM2NiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rbvoij4zyhANp3Pl-rlVJvZ4GpC8hMIbb-9TNJnDBKs)
> 
> 修改DNS为114.114.114.114之类的

是 config.toml里的 dns吗

**Comment by jonm58** [comment]
> > > > > > > "hdslb.com": 1,
> > > > > > 
> > > > > > 
> > > > > > 加了一级域名，其子域名也会走 Accesser，不必再加 i1.hdslb.com
> > > > > 
> > > > > 
> > > > > 开始我是只加了hdslb.com，还是访问不了，所以尝试加了 i1.hdslb.com
> > > > 
> > > > 
> > > > 访问不了是因为证书校验问题，关闭校验就行了
> > > 
> > > 
> > > 这是我fork https://github.com/conanlm/Accesser 的地址 还是不行，b站页面能打开了，但是hdslb.com地址还是加载不了 ![图片_lanxin_20240716104856](https://private-user-images.githubusercontent.com/2777986/348922657-3c407402-c688-4aca-9c82-a58264ea89ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwOTkxMTYsIm5iZiI6MTcyMTA5ODgxNiwicGF0aCI6Ii8yNzc3OTg2LzM0ODkyMjY1Ny0zYzQwNzQwMi1jNjg4LTRhY2EtOWM4Mi1hNTgyNjRlYTg5YWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTZUMDMwMDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDZkOTM0NjcxMWVhYjAzY2ZhMjIwMjZmNzZhNTM5M2U1MGY3YWY0YTQ3YzlhZTcwNGRkMWU5NTUwNjhiM2NiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rbvoij4zyhANp3Pl-rlVJvZ4GpC8hMIbb-9TNJnDBKs)
> > 
> > 
> > 修改DNS为114.114.114.114之类的
> 
> 是 config.toml里的 dns吗

是的

**Comment by conanlm** [comment]
> > > > > > > > "hdslb.com": 1,
> > > > > > > 
> > > > > > > 
> > > > > > > 加了一级域名，其子域名也会走 Accesser，不必再加 i1.hdslb.com
> > > > > > 
> > > > > > 
> > > > > > 开始我是只加了hdslb.com，还是访问不了，所以尝试加了 i1.hdslb.com
> > > > > 
> > > > > 
> > > > > 访问不了是因为证书校验问题，关闭校验就行了
> > > > 
> > > > 
> > > > 这是我fork https://github.com/conanlm/Accesser 的地址 还是不行，b站页面能打开了，但是hdslb.com地址还是加载不了 ![图片_lanxin_20240716104856](https://private-user-images.githubusercontent.com/2777986/348922657-3c407402-c688-4aca-9c82-a58264ea89ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwOTkxMTYsIm5iZiI6MTcyMTA5ODgxNiwicGF0aCI6Ii8yNzc3OTg2LzM0ODkyMjY1Ny0zYzQwNzQwMi1jNjg4LTRhY2EtOWM4Mi1hNTgyNjRlYTg5YWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTZUMDMwMDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDZkOTM0NjcxMWVhYjAzY2ZhMjIwMjZmNzZhNTM5M2U1MGY3YWY0YTQ3YzlhZTcwNGRkMWU5NTUwNjhiM2NiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rbvoij4zyhANp3Pl-rlVJvZ4GpC8hMIbb-9TNJnDBKs)
> > > 
> > > 
> > > 修改DNS为114.114.114.114之类的
> > 
> > 
> > 是 config.toml里的 dns吗
> 
> 是的

还是不太行，午休期间是可以正常访问的。
不开软件正常访问，打开软件，就加载不正常了

**Comment by jonm58** [comment]
CORS?

**Comment by conanlm** [comment]
> CORS? 还是*.hdslb.com的IP被屏蔽了?

![image](https://github.com/user-attachments/assets/8e9797cc-b513-430c-b97d-67d9a4ced47a)

**Comment by jonm58** [comment]
用Accesser访问www.gov.cn可能有问题

**Comment by conanlm** [comment]
> 加上这些试试看
> 
> ```
> s1.hdslb.com
> s2.hdslb.com
> s3.hdslb.com
> i0.hdslb.com
> i1.hdslb.com
> i2.hdslb.com
> i3.hdslb.com
> ```
> 
> 去掉hdslb.com

没什么变化

**Comment by jonm58** [comment]
你测试一下
https://s1.hdslb.com/bfs/space/6bcf4599696f7aec0bd6ebd3693beb82c7fedb25.png
https://s2.hdslb.com/bfs/space/6bcf4599696f7aec0bd6ebd3693beb82c7fedb25.png
https://s3.hdslb.com/bfs/space/6bcf4599696f7aec0bd6ebd3693beb82c7fedb25.png
https://i0.hdslb.com/bfs/space/6bcf4599696f7aec0bd6ebd3693beb82c7fedb25.png
https://i1.hdslb.com/bfs/space/6bcf4599696f7aec0bd6ebd3693beb82c7fedb25.png
https://i2.hdslb.com/bfs/space/6bcf4599696f7aec0bd6ebd3693beb82c7fedb25.png
https://i3.hdslb.com/bfs/space/6bcf4599696f7aec0bd6ebd3693beb82c7fedb25.png

找个可以使用的hdslb.com进行替换

**Comment by conanlm** [comment]
> 你测试一下 https://s1.hdslb.com/bfs/space/6bcf4599696f7aec0bd6ebd3693beb82c7fedb25.png https://s2.hdslb.com/bfs/space/6bcf4599696f7aec0bd6ebd3693beb82c7fedb25.png https://s3.hdslb.com/bfs/space/6bcf4599696f7aec0bd6ebd3693beb82c7fedb25.png https://i0.hdslb.com/bfs/space/6bcf4599696f7aec0bd6ebd3693beb82c7fedb25.png https://i1.hdslb.com/bfs/space/6bcf4599696f7aec0bd6ebd3693beb82c7fedb25.png https://i2.hdslb.com/bfs/space/6bcf4599696f7aec0bd6ebd3693beb82c7fedb25.png https://i3.hdslb.com/bfs/space/6bcf4599696f7aec0bd6ebd3693beb82c7fedb25.png
> 
> 找个可以使用的hdslb.com进行替换

是在不开软件时，打开上面页面吗，都打不开啊😭

**Comment by jonm58** [comment]
在开软件时，打开上面页面

**Comment by conanlm** [comment]
> 在开软件时，打开上面页面

开着也不行，这个有没有涉及到缓存啊，会不会产生影响
其实我不是很懂这个原理😅

**Comment by jonm58** [comment]
在[http_redirect]里
"tumblr.com/" = "www.tumblr.com/"
"tumblr.com/" = "www.tumblr.com/"
[alter_hostname]

**Comment by jonm58** [comment]
在[http_redirect]里
"s1.hdslb.com/" = "i0.hdslb.com/"
"s2.hdslb.com/" = "i0.hdslb.com/"
"s3.hdslb.com/" = "i0.hdslb.com/"
"i1.hdslb.com/" = "i0.hdslb.com/"
"i2.hdslb.com/" = "i0.hdslb.com/"
"i3.hdslb.com/" = "i0.hdslb.com/"

在[alter_hostname]里
"i0.hdslb.com" = "xn--6iq3kq43dsq8aeuj.alicdn.com"

在[hosts]里
"i0.hdslb.com" = "121.194.10.88"

**Comment by conanlm** [comment]
有部分可以了，但是视频还是加载不出来
![image](https://github.com/user-attachments/assets/35ffa315-f373-4beb-aa36-02c57f6ec975)

**Comment by jonm58** [comment]
在[alter_hostname]里
"upos-sz-mirror08c.bilivideo.com" = "appgallery.huawei.com"
"upos-sz-mirror08h.bilivideo.com" = "appgallery.huawei.com"
"upos-sz-mirrorcos.bilivideo.com" = "xn--()-o13aus685jthap52adx4b1ccrsrl91bxbdwr5apudf51i.cdn.myqcloud.com"
"upos-sz-mirrorcosb.bilivideo.com" = "luna_say_maybe.a.yximgs.com"
"upos-sz-mirrorbos.bilivideo.com" = "xn--n8jz80g4b554aznsbs2alsg.a.bdydns.com"
"upos-sz-mirrorhw.bilivideo.com" = "xn--cckea33a.ctcdn.cn"
"upos-sz-mirrorhwb.bilivideo.com" = "yellow_big_bang!.ctcdn.cn"

在[cert_verify]里
"upos-sz-mirror08c.bilivideo.com" = ["appgallery.huawei.com"]
"upos-sz-mirror08h.bilivideo.com" = ["appgallery.huawei.com"]
"upos-sz-mirrorcos.bilivideo.com" = ["cdn.myqcloud.com"]
"upos-sz-mirrorcosb.bilivideo.com" = ["a.yximgs.com", "a.etoote.com", "a.yximgs.com"]
"upos-sz-mirrorbos.bilivideo.com" = ["a.bdydns.com"]
"upos-sz-mirrorhw.bilivideo.com" = ["ctcdn.cn"]
"upos-sz-mirrorhwb.bilivideo.com" = ["ctcdn.cn"]

在[hosts]里
"upos-sz-mirror08c.bilivideo.com" = "121.194.10.211"
"upos-sz-mirror08h.bilivideo.com" = "121.194.10.211"
"upos-sz-mirrorcos.bilivideo.com" = "61.240.216.135"
"upos-sz-mirrorcosb.bilivideo.com" = "116.162.124.9"
"upos-sz-mirrorbos.bilivideo.com" = "182.140.225.41"
"upos-sz-mirrorhw.bilivideo.com" = "118.123.20.59"
"upos-sz-mirrorhwb.bilivideo.com" = "220.163.254.25"

**Comment by conanlm** [comment]
> 在[alter_hostname]里 "upos-sz-mirror08c.bilivideo.com" = "appgallery.huawei.com" "upos-sz-mirror08h.bilivideo.com" = "appgallery.huawei.com" "upos-sz-mirrorcos.bilivideo.com" = "xn--()-o13aus685jthap52adx4b1ccrsrl91bxbdwr5apudf51i.cdn.myqcloud.com" "upos-sz-mirrorcosb.bilivideo.com" = "luna_say_maybe.a.yximgs.com" "upos-sz-mirrorbos.bilivideo.com" = "xn--n8jz80g4b554aznsbs2alsg.a.bdydns.com" "upos-sz-mirrorhw.bilivideo.com" = "xn--cckea33a.ctcdn.cn" "upos-sz-mirrorhwb.bilivideo.com" = "yellow_big_bang!.ctcdn.cn"
> 
> 在[cert_verify]里 "upos-sz-mirror08c.bilivideo.com" = ["appgallery.huawei.com"] "upos-sz-mirror08h.bilivideo.com" = ["appgallery.huawei.com"] "upos-sz-mirrorcos.bilivideo.com" = ["cdn.myqcloud.com"] "upos-sz-mirrorcosb.bilivideo.com" = ["a.yximgs.com", "a.etoote.com", "a.yximgs.com"] "upos-sz-mirrorbos.bilivideo.com" = ["a.bdydns.com"] "upos-sz-mirrorhw.bilivideo.com" = ["ctcdn.cn"] "upos-sz-mirrorhwb.bilivideo.com" = ["ctcdn.cn"]
> 
> 在[hosts]里 "upos-sz-mirror08c.bilivideo.com" = "121.194.10.211" "upos-sz-mirror08h.bilivideo.com" = "121.194.10.211" "upos-sz-mirrorcos.bilivideo.com" = "61.240.216.135" "upos-sz-mirrorcosb.bilivideo.com" = "116.162.124.9" "upos-sz-mirrorbos.bilivideo.com" = "182.140.225.41" "upos-sz-mirrorhw.bilivideo.com" = "118.123.20.59" "upos-sz-mirrorhwb.bilivideo.com" = "220.163.254.25"

大善人啊，可以加载视频了
这么耐心，把配置写好给我，真的好久没遇到这么好的人了😹

**Comment by jonm58** [comment]
![图片](https://github.com/user-attachments/assets/af824b73-809e-47d9-8146-2587bba25d06)

**Comment by conanlm** [comment]
> ![图片](https://private-user-images.githubusercontent.com/73036321/349002739-af824b73-809e-47d9-8146-2587bba25d06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMTkyMzQsIm5iZiI6MTcyMTExODkzNCwicGF0aCI6Ii83MzAzNjMyMS8zNDkwMDI3MzktYWY4MjRiNzMtODA5ZS00N2Q5LTgxNDYtMjU4N2JiYTI1ZDA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA4MzUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkODg0MGMzMzU5MjI1MTIxMzBkNTQ0NjRmNWVlNDQ0MDMyYmY2MzkwNDI5ZTdkNDljZjY2YTc1YzhhZmZhY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.303F4UN5SMtD6twWQvo4v3gFBkxdlon2LYVlBg88Ku8)

谢谢🙏

**Comment by jonm58** [comment]
> > ![图片](https://private-user-images.githubusercontent.com/73036321/349002739-af824b73-809e-47d9-8146-2587bba25d06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMTkyMzQsIm5iZiI6MTcyMTExODkzNCwicGF0aCI6Ii83MzAzNjMyMS8zNDkwMDI3MzktYWY4MjRiNzMtODA5ZS00N2Q5LTgxNDYtMjU4N2JiYTI1ZDA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA4MzUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkODg0MGMzMzU5MjI1MTIxMzBkNTQ0NjRmNWVlNDQ0MDMyYmY2MzkwNDI5ZTdkNDljZjY2YTc1YzhhZmZhY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.303F4UN5SMtD6twWQvo4v3gFBkxdlon2LYVlBg88Ku8)
> 
> 谢谢🙏

关闭issue

**Comment by Xihihhh** [comment]
运行日志 don't match either of 后面的一大堆域名选一个也行。

奇怪，我这只要关闭证书校验再用国内 DNS 就可以了，不会有”don't match either of “提示。🤔
