### ISSUE TITLE
关于Matrix

### ISSUE THREAD

**Issue by louiesun** [URenko/Accesser#179]
确实，通过域前置，我能上matrix(客户端挨批评。element.io)聊天了。（而且是cloudflare的前置，matrix故意打开了域前置）。

但是不翻却注册不了。

具体症状：

recaptcha无法加载：
https://www.gstatic.cn/recaptcha/releases/Xv-KF0LlBu_a0FJ9I5YSlX5m/recaptcha__zh_cn.js

但是呢，如果你复制这个链接再在新标签页打开时可以的。

![image](https://github.com/user-attachments/assets/85f5655b-6393-4891-bd03-3f8cf8523bf3)

有没有人帮忙诊断一下？

配置：
```text
IP: 104.20.76.252
www.matrix.org
matrix.org
matrix-client.matrix.org
```

**Comment by Xihihhh** [comment]
还有[https://matrix-client.matrix.org/_matrix/client/v3/register](https://matrix-client.matrix.org/_matrix/client/v3/register) 401 Unauthorized。可以 SSO 注册。

**Comment by louiesun** [comment]
> 还有https://matrix-client.matrix.org/_matrix/client/v3/register 401 Unauthorized。可以 SSO 注册。

啥意思？哪两个网站共享？

**Comment by Xihihhh** [comment]
> > 还有https://matrix-client.matrix.org/_matrix/client/v3/register 401 Unauthorized。可以 SSO 注册。
> 
> 啥意思？哪两个网站共享？

注册页面可从 GitHub、Google 等网站注册

**Comment by louiesun** [comment]
> > > 还有https://matrix-client.matrix.org/_matrix/client/v3/register 401 Unauthorized。可以 SSO 注册。
> > 
> > 
> > 啥意思？哪两个网站共享？
> 
> 注册页面可从 GitHub、Google 等网站注册

哦，试过了，可以，谢谢。

所以有人能解释这个灵异事件吗？

**Comment by UjuiUjuMandan** [comment]
从控制台的 Console 和 Network 肯定能看到错误信息呗，应该是什么头里的安全策略。

**Comment by linsui** [comment]
https://github.com/element-hq/element-web/issues/12137

**Comment by louiesun** [comment]
> [element-hq/element-web#12137](https://github.com/element-hq/element-web/issues/12137)

完全一致
