### ISSUE TITLE
功能请求：允许其他设备接入

### ISSUE THREAD

**Issue by linsui** [URenko/Accesser#18]
希望可以添加一个选项，允许其他设备使用此代理，谢谢 :smile:

**Comment by URenko** [comment]
目前比较忙，更新会比较慢
手动的方法是把accesser.py里的`server_address = ('127.0.0.1', 7655)`改成`server_address = ('0.0.0.0', 7655)`

**Comment by linsui** [comment]
谢谢 :+1:

**Comment by linsui** [comment]
可以工作，不过我无法将证书导入 Firefox for Android，搜索到的方法，一种是将证书转为pem格式然后通过浏览器下载，但没有起作用。另一种需要 root 后通过 adb 操作，没有尝试。如果有人成功了还请不吝赐教 :joy:
有个不太相关的问题想请教一下：我只要使用 vscode 编辑过代码就会出现
```python
Traceback (most recent call last):
  File "accesser.py", line 29, in <module>
    from utils import webui
ModuleNotFoundError: No module named 'utils'
```
但记事本编辑就没问题。不知道是什么原因

**Comment by URenko** [comment]
@linsui 是在vscode里启动吗，可能是vscode启动的工作位置不太对的问题

**Comment by linsui** [comment]
我发现原因是 autopep8 自动格式化把  `sys.path.append(os.path.dirname(__file__))` 放到了 import 后面，一直没注意到。:joy:

**Comment by linsui** [comment]
将证书导入 Firefox for Android 的问题找到解决方案了，代码如下供参考

```python
import http.server
import socketserver
PORT = 8000
Handler = http.server.SimpleHTTPRequestHandler
Handler.extensions_map = {
    '.crt': 'application/x-x509-ca-cert', '.txt': 'text/plain'}
httpd = socketserver.TCPServer(("", PORT), Handler)
print("serving at port", PORT)
httpd.serve_forever()
```

在证书所在目录运行这段代码，然后在 Firefox for Android 中访问 PC 的 8000 端口下载证书文件即可。
[参考链接](https://mtersch.wordpress.com/2015/03/17/certificate-import-in-firefox-on-android/)
或许可以直接集成这一功能? :joy:

**Comment by URenko** [comment]
这个方法好👍
