### ISSUE TITLE
借地提问：关于教育网

### ISSUE THREAD

**Issue by louiesun** [URenko/Accesser#180]
之前去了我高中学校机房（上海某四校分）。

结果发现那个鬼地方Cloudflare快的要死，我访问pixiv秒出。（http3）

后来看了一眼，这玩意ping 104的IP延迟只有20ms-30ms，而我们家移动是200-300ms.

教育网这么神奇的吗？

**Comment by jonm58** [comment]
> 后来看了一眼，这玩意ping 104的IP延迟只有20ms-30ms，而我们家移动是200-300ms.

看看你家移动过了多少给服务器(好奇
