### ISSUE TITLE
assets.twitch.tv 报错

### ISSUE THREAD

**Issue by Pony-CW** [URenko/Accesser#181]
![ResizedImage_2024-08-12_11-23-30_1](https://github.com/user-attachments/assets/4442dce0-dc83-4029-9167-eef1c8d2dc1c)
> 咱表示截图比复制日志可能会更好，嗯

Termux-Monet 启动 Accesser，使用 Clash-Meta 规则转发至 Accesser，浏览器使用 Iceraven，已安装用户级 root 根证书

由于这个域名不加载的话 twitch 啥也加载不出，而我说实话又不怎么懂这些网络层的东西是吧，所以看看这里能不能有人解决以下咯

提前谢谢了

**Comment by Xihihhh** [comment]
[assets.twitch.tv](https://assets.twitch.tv)得走代理 ~~，或者试试 TCB 脱同步~~。这个域名用了 CloudFront CDN，网站又没开 CNAME。

**Comment by Xihihhh** [comment]
现在可以了，尝试从源码安装：
```
pip3 install -U "accesser[doh,doq] @ git+https://github.com/URenko/Accesser.git"
```

**Comment by Pony-CW** [comment]
既然有做尝试，那我过来反馈问题了
![Screenshot_2024-08-16-13-15-30-22_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/user-attachments/assets/52f9f28f-b620-45b0-b4f3-e35d4f581130)

**Comment by Xihihhh** [comment]
不好意思，忘记开宽松证书校验了…… 下载[https://raw.githubusercontent.com/Xihihhh/Accesser/patch-1/accesser/config.toml](https://raw.githubusercontent.com/Xihihhh/Accesser/patch-1/accesser/config.toml)放在你运行accesser的目录下
```
curl -O https://raw.githubusercontent.com/Xihihhh/Accesser/patch-1/accesser/config.toml
```

**Comment by Pony-CW** [comment]
```
2024-08-16 15:10:29 DEBUG    Accesser: [56572] DNS: m.twitch.tv -> 151.101.2.214                                                    2024-08-16 15:10:29 DEBUG    Accesser: [56572] server_hostname=''
2024-08-16 15:10:29 DEBUG    Accesser: [56572] subjectAltName: (('DNS', 'twitch.tv'), ('DNS', '*.twitch.tv')), subject: ((('commonName', 'twitch.tv'),),).
2024-08-16 15:10:29 WARNING  Accesser: [56572] ['cloudfront.net'] don't match either of subjectAltName: (('DNS', 'twitch.tv'), ('DNS', '*.twitch.tv')), subject: ((('commonName', 'twitch.tv'),),).
```

我本来想说又出问题了，然后一看你配置，显然是忘了手机端域名 m.twitch.tv 🤣我自己加上后就确实真的可以直连了

```
[cert_verify]
...
 "m.twitch.tv" = ["m.twitch.tv"]
```

多谢出手相助

**Comment by Xihihhh** [comment]
坏了，一堆其他网站移动端域名没加😅从来没注意到

**Comment by SpaceTimee** [comment]
我无法使用 Accesser 访问 Twitch

Accesser 输出:
![image](https://github.com/user-attachments/assets/5f8006a7-7866-42e4-8f51-0ab88dc35898)

网页报错:
![{D5B6C845-8C91-421A-8705-AE744C6F5A97}](https://github.com/user-attachments/assets/55ed2ee3-17ee-4edc-89d3-77908ef29d19)

同时测试的 Pixiv 和 Wikipedia 访问正常

运行环境: Win11 x64, Python 3.12.4, Accesser 使用最新的 commit

**Comment by URenko** [comment]
你用的 DNS 被墙了，换个 `[DNS]` 或者写死 `[hosts]`

**Comment by Xihihhh** [comment]
我这配置里的也都超时了，下面的都还能用：
```
https://9.9.9.9/dns-query
https://9.9.9.10/dns-query
https://9.9.9.11/dns-query
tls://9.9.9.9
tls://9.9.9.10
tls://9.9.9.11
```
来自[quad9.net](https://quad9.net)

**Comment by SpaceTimee** [comment]
我通过写死 hosts 解决了，`"www.twitch.tv" = "151.101.194.167"`，确实可用
