### ISSUE TITLE
部分网站证书不被接受

### ISSUE THREAD

**Issue by P-256** [URenko/Accesser#19]
某些网站无法通过代理，提示ERR_EMPTY_RESPONSE，未发送数据
如https://cn.nikkei.com/
并且有时开了cmd或者是没清除log就可能无法启动成功。

**Comment by URenko** [comment]
Selecting DoH server等了多久，网不好有的时候会比较慢 @P-256

**Comment by P-256** [comment]
> Selecting DoH server等了多久，网不好有的时候会比较慢 @P-256

无线满格，但等了一两分钟Selecting DoH server提示直接消失

**Comment by P-256** [comment]
> Selecting DoH server等了多久，网不好有的时候会比较慢 @P-256

而且某些网站无法通过代理，提示ERR_EMPTY_RESPONSE，未发送数据
如https://cn.nikkei.com/

**Comment by P-256** [comment]
> Selecting DoH server等了多久，网不好有的时候会比较慢 @P-256

现在貌似好了

**Comment by URenko** [comment]
@P-256 Selecting DoH server本来就是会自动消失的（所有消息都一样），DoH启动速度主要取决于服务器的速度，虽然我加了好几个服务器，不过好像都比较慢😂，或许可以考虑其他的DNS方案（已经加了接口），比如 #12 里的dnsforwarder之类的。
至于 https://cn.nikkei.com/ ，可能是这个网站的证书有问题，Firefox和Python都不接受，只有Windows接受
[境外的Python访问测试](https://www.tutorialspoint.com/tpcg.php?p=NYpdNe)

**Comment by P-256** [comment]
> @P-256 Selecting DoH server本来就是会自动消失的（所有消息都一样），DoH启动速度主要取决于服务器的速度，虽然我加了好几个服务器，不过好像都比较慢😂，或许可以考虑其他的DNS方案（已经加了接口），比如 #12 里的dnsforwarder之类的。
> 至于 https://cn.nikkei.com/ ，可能是这个网站的证书有问题，Firefox和Python都不接受，只有Windows接受
> [境外的Python访问测试](https://www.tutorialspoint.com/tpcg.php?p=NYpdNe)

貌似使用Amzon AWS的几乎所有网站都会拒绝此证书。昨天试验了NicoNico的几个使用AWS的域名也是这样，有什么方法解决吗？

**Comment by URenko** [comment]
@P-256 哪些域名

**Comment by P-256** [comment]
site.nicovideo.jp
blog.nicovideo.jp
info.nicovideo.jp

**Comment by P-256** [comment]
> @P-256 哪些域名

site.nicovideo.jp
blog.nicovideo.jp
info.nicovideo.jp

**Comment by URenko** [comment]
niconico这个跟上面的不太一样，是服务器那边拒绝了连接，可能是因为Amazon受到俄罗斯政府压力
暂无好的解决方案

**Comment by SeaHOH** [comment]
https://cn.nikkei.com/ 未配置完整的证书链，需要客户端自己下载缺少的 CA。
浏览器都有实现，pyOpenSSL 没有，需要自己写。
这个还好，验证撤销更麻烦。

**Comment by URenko** [comment]
我们选择采取和Firefox一样的态度：这是网站的配置失误。所以不针对这一问题进行修复。
