### ISSUE TITLE
tumblr 无效

### ISSUE THREAD

**Issue by Pony-CW** [URenko/Accesser#193]
我又过来了——
看 wiki 和 pac 文件都写着，结果我从一开始用这个软件直到现在，莫得用

域名解析如下
![ResizedImage_2024-08-29_22-09-50_2542.jpg](https://github.com/user-attachments/assets/4fb6eebf-9b8a-4aaf-8173-84855f3b5cba)
> 不会又是什么 cf cdn 吧

**Comment by Xihihhh** [comment]
不是，`192.0.77.40`黑洞了，似乎 Desync 也没能解决。

> 看 wiki 和 pac 文件都写着，结果我从一开始用这个软件直到现在，莫得用

wiki 那列表很久没更新了，pac 所写不一定支持。

**Comment by URenko** [comment]
那就删掉吧
