### ISSUE TITLE
www.reddit.com 页面加载异常

### ISSUE THREAD

**Issue by Pony-CW** [URenko/Accesser#200]
> 嗯……天天跑过来，真是打扰开发者了

咱不知道怎么回事，日志和现状伺候
![ResizedImage_2024-09-17_20-07-19_7508.jpg](https://github.com/user-attachments/assets/7049c8ba-5981-41ef-b8ed-cb2087233f9f)

右边是 termux-x11 xfce 上的 firefox，已安装根证书
因为我那 iceraven (firefox fork) 没法加载，就换接近桌面环境的 firefox，结果也不行
最新 config.toml

**Comment by jonm58** [comment]
各个网站通过证书证明自己的身份。Firefox不能信任此网站，你使用IP的证书对Reddit无效。该证书只适用于下列名称： *.reddit.com, reddit.com
错误代码：SSL_ERROR_BAD_CERT_DOMAIN

**Comment by jonm58** [comment]
reddit不支持ECH和http3
你只能试试TCB脱同步了

**Comment by louiesun** [comment]
> reddit不支持ECH和http3 你只能试试TCB脱同步了

不在北上广。还可以试试ttl。

**Comment by jonm58** [comment]
![图片](https://github.com/user-attachments/assets/5ec1df16-b540-4b32-9e0c-8af466631e22)

**Comment by jonm58** [comment]
![图片](https://github.com/user-attachments/assets/02f4bdc8-27b0-4ebb-81ad-9ecdac464664)

**Comment by Pony-CW** [comment]
uh...他自己恢复正常了，纳闷

**Comment by zdm9981** [comment]
*.redd.it 失效了

Requested host does not match any Subject Alternative Names (SANs) on TLS certificate in use with this connection.

Visit https://docs.fastly.com/en/guides/common-400-errors#error-421-misdirected-request for more information.

**Comment by louiesun** [comment]
> 因为不能用 fastly.com，Fastly 网站差不多都失效了。
> Reddit 的策略较松，主域名可以连接。
> mastodon.social 没办法了，不过可以找其他实例。
> Disqus 这样的有专属 IP，所以没事。
> 其他都未测试，因为全都443超时了。

mastodon可以用tls分片，部署在传输层。无需管理，termux可运行
缺点是需手动配置 
https://github.com/maoist2009/TLSfragment
根据DPYproxy的数据，90%的网站都支持。
建议配上switchproxyomega

**Comment by jonm58** [comment]
![ezgif com-apng-to-avif-converter avif](https://github.com/user-attachments/assets/0913667a-2239-4079-8166-6f80c61cf665)
![1-ezgif com-apng-to-avif-converter avif](https://github.com/user-attachments/assets/6f02fd92-cf97-4bdd-9519-a204df76e127)
