### ISSUE TITLE
[bug]每次使用需要在firefox中重新导入证书

### ISSUE THREAD

**Issue by itissad** [URenko/Accesser#204]
importca = false
疑似原因是每次运行程序时都会生成新的证书, 如果不在firefox中重新导入证书，会无法打开网页，显示对等端证书错误

**Comment by itissad** [comment]
在importca = false的条件下，每次启动CERT下的root.crt的sha1值不同，说明其是新生成的

**Comment by URenko** [comment]
pip 安装还是 Windows exe

**Comment by itissad** [comment]
> pip 安装还是 Windows exe

Windows exe 和 git clone 后运行accesser.py 都试过，效果一样

**Comment by itissad** [comment]
> pip 安装还是 Windows exe

好快的修复，刚想提个pr
