### ISSUE TITLE
提交到 scoop

### ISSUE THREAD

**Issue by linsui** [URenko/Accesser#21]
我准备将 Accesser 提交到 scoop 仓库。Scoop 通过清单文件安装应用，使用硬链接保存配置文件。我不知道如果直接运行的话如何在更新时保留 CERT 文件夹和 pac 文件，所以采用的是解压后创建 CERT 文件夹，通过 vbs 脚本运行的方式。这种方法不会出现一闪而过的 cmd 窗口。所以请问有其他方法吗？

**Comment by URenko** [comment]
目前在准备使用pyinstaller

**Comment by linsui** [comment]
啊，重点不是这个，是配置文件存放位置和更新方式 :joy: 。请问目前配置文件存放在哪里？下个版本会如何处理？

**Comment by URenko** [comment]
按照下一版本的pyinstaller处理，是内置一份config.json.default，如果配置有修改就同目录下保存一份config.json，CERT文件夹在临时文件夹，目前证书自动生成（根证书在WIndows储存区），所以不用管它

**Comment by linsui** [comment]
scoop 直接下载打包发布的文件。这样的话就不需要做什么了，单文件是最方便的。 :+1:

**Comment by linsui** [comment]
scoop 要求一个英文描述 How about “A tool which can help you bypass SNI RST”

**Comment by URenko** [comment]
pac是在template中，参见仓库里代码的结构，不过有未来不再手动修改pac的计划，所以未写入wiki。
英文描述OK

**Comment by linsui** [comment]
如果 Accesser.exe + config.json 的结构不变就没有影响，目前scoop清单仅涉及这两个文件。pr 在[这里](https://github.com/lukesampson/scoop-extras/pull/1968)

**Comment by linsui** [comment]
现在已经可以通过 `scoop install accesser` 安装
