### ISSUE TITLE
请求添加设置不自动在浏览器中打开webui

### ISSUE THREAD

**Issue by LKGin** [URenko/Accesser#22]
直接注释掉webbrowser.open('http://localhost:7654/')这行，发现还是要浏览器手动打开http://localhost:7654才生效

**Comment by URenko** [comment]
应该不是要手动打开才生效，是选择DoH服务器时间较长的错觉吧

**Comment by LKGin** [comment]
> 应该不是要手动打开才生效，是选择卫生部服务器时间较长的错觉吧

还真的是这样，囧~

**Comment by LKGin** [comment]
> 应该不是要手动打开才生效，是选择卫生部服务器时间较长的错觉吧

另外，能不能把101.101.101.101的DOH也加进去，主要是这个电信线路还行。
https://blog.twnic.net.tw/2018/12/28/1803/
https://blog.twnic.net.tw/2018/07/02/1086/

**Comment by URenko** [comment]
非常感谢，最近正缺少较快的DoH服务器

**Comment by URenko** [comment]
现在设置config.json中的`"webui"`选项或者使用命令行参数`--cli`即可
