### ISSUE TITLE
能不能做一个只防dns污染的pac

### ISSUE THREAD

**Issue by P-256** [URenko/Accesser#24]
1.由于目前墙针对封锁视频网站都使用封锁视频源，比如niconico封锁dmc.nico，twitch封锁ttntv.net，但使用普通的防污染DNS可能有时还会被污染。
2.还找到一批新的网站：（慢慢更）
德国之声（部分使用akamai的域名拒绝连接）
imgur
3.dropbox有时候会出问题啊，目前主站的IP除了伦敦的之外全部黑名单，但用伦敦IP会长时间卡死响应（不是未发送数据）

**Comment by miaomiaosoft** [comment]
ttvnw.net并没有被封锁
dmc.nico也没有被封锁
你用的所谓防污染DNS可能防污染没做好，基于列表而不是自动识别的防污染DNS经常能遇到部分域名被污染，要反馈给提供者人工增加，可以换成中科大或清华的DNS
imgur和德国之声都可以用Accesser正常访问

**Comment by URenko** [comment]
不是基于UDP的防污染DNS解决方案已经有很多了，所以短期内不考虑单独支持，比如用这个项目依赖的dohproxy一行代码就可以使用：
`pythonw -m dohproxy.stub --listen-port 53 --listen-address 127.0.0.1 --domain ea-dns.rubyfish.cn`
dropbox我这似乎没问题？使用的就是你之前 #13 里的IP

**Comment by P-256** [comment]
找到了几个新IP待会试试。现在dropbox的IP不太好找了，扫了一下段几乎全都挂了。
imgur的ip
151.101.100.193	imgur.com
151.101.100.193	m.imgur.com
151.101.100.193	api.imgur.com
151.101.100.193	www.imgur.com
151.101.100.193	store.imgur.com
151.101.100.193	s.imgur.com
151.101.100.193	p.imgur.com
151.101.100.193	i.imgur.com

**Comment by URenko** [comment]
imgur似乎也没有IP上的问题？dropbox我这基本都行啊

**Comment by P-256** [comment]
伦敦的IP能用，圣何塞的IP几乎全部被墙，东京香港法兰克福的都不能用。顺便一提测试环境：电信，tcp看了一下到广州就黑洞

**Comment by P-256** [comment]
另外问一下，*.whatapp.net已经被证书检测了那么加IP意义何在

**Comment by URenko** [comment]
欸？原来是证书检测吗，我还以为是TLS1.3的原因，所以一直放着以后研究，有相关来源吗？
路由黑洞的问题我再多检测看看，现在都这么普及了吗😓

**Comment by P-256** [comment]
确实证书检测了，貌似去年才加的，我今年看到这个网址托管到AWS了改了一下IP发现更本没法访问和fb，google封锁方式一样。
路由黑洞已经不像几年前了，现在基本上封IP都是黑洞

**Comment by P-256** [comment]
> 欸？原来是证书检测吗，我还以为是TLS1.3的原因，所以一直放着以后研究，有相关来源吗？
> 路由黑洞的问题我再多检测看看，现在都这么普及了吗😓

dropbox可以移除了，等了一分多钟弄出来个未发送数据

**Comment by URenko** [comment]
dropbox我试了下，电信大概是黑洞了，移动可以上，故暂不移除

**Comment by LKGin** [comment]
> Dropbox的我试了下，电信大概是黑洞了，移动可以上，故暂不移除

FAQ能不能写下导入证书的手动方法，自从6.0版本后就没见导入成功过。

**Comment by LKGin** [comment]
> Dropbox的我试了下，电信大概是黑洞了，移动可以上，故暂不移除

导入证书的机制实在太拉闸了，自从6.0版本就没见过自动导入过，都是用5.0凑合搭上的，现在6.1版本手动导入根证书后，打开任意sni网页，下级证书又没匹配成功，都是accesser_proxy，该证书有一个无效的数字签名

**Comment by URenko** [comment]
@LKGin 建议把Accesser相关的证书全清掉重来，主要是“个人”和“受信任的根证书颁发机构”两个地方，Firefox见wiki
虽然无限打开，但是真正运行的还是第一个
另：最好另开issue

**Comment by P-256** [comment]
> @LKGin 建议把Accesser相关的证书全清掉重来，主要是certmgr.msc中“个人”和“受信任的根证书颁发机构”两个地方，Firefox见wiki
> 虽然无限打开，但是真正运行的还是第一个
> 另：最好另开issue

还有几个网站：
www.epochtimes.com 经济学人
www.euronews.com 歐洲新聞台
line.me  部分界面有问题
reuters.com 路透社
www.cna.com.tw 中央社

**Comment by URenko** [comment]
> 还有几个网站：
> www.epochtimes.com 经济学人
> www.euronews.com 歐洲新聞台
> line.me  部分界面有问题
> reuters.com 路透社
> www.cna.com.tw 中央社

像这种确定的直接pr好了😅

**Comment by linsui** [comment]
> 
> 
> > 还有几个网站：
> > [www.epochtimes.com](http://www.epochtimes.com) 经济学人
> > [www.euronews.com](http://www.euronews.com) 歐洲新聞台
> > line.me  部分界面有问题
> > reuters.com 路透社
> > [www.cna.com.tw](http://www.cna.com.tw) 中央社
> 
> 像这种确定的直接pr好了sweat_smile

有没有包含政策？比如 googlehosts 拒绝 NSFW？另外建议把支持 ESNI 的网站分开，防止冲突。

**Comment by URenko** [comment]
对于pac，暂无包含政策，只要可用即可，wiki中会看情况筛选
ESNI的话，考虑到目前支持还不多，就先放着。实际上域名配置还没确定好方案，做个自动识别也说不定

**Comment by uicba** [comment]
> 
> 还有几个网站：
> [www.epochtimes.com](http://www.epochtimes.com) 经济学人
> [www.euronews.com](http://www.euronews.com) 歐洲新聞台
> line.me 部分界面有问题
> reuters.com 路透社
> [www.cna.com.tw](http://www.cna.com.tw) 中央社

你确定是epochtimes是经济学人？

**Comment by linsui** [comment]
😂 经济学人倒也 RST 了
