### ISSUE TITLE
0.6.1几个小问题

### ISSUE THREAD

**Issue by miaomiaosoft** [URenko/Accesser#25]
WEB控制页里的关闭点了后进程不会消失，也就是不会关闭，难道只是关闭WEB？

能不能增加选项，启动后不自动设置PAC，PAC设置可能对普通用户比较方便，但我觉得用浏览器扩展Proxy SwitchyOmega代替会更灵活。

好像不生成配置文件，每次重启都是默认配置，手工复制一份config.json.default改成config.json放到程序目录倒是可以解决
2019-04-13 21:48:58 WARNING  tornado.access: 404 GET /configfile (127.0.0.1) 0.00ms

**Comment by URenko** [comment]
> WEB控制页里的关闭点了后进程不会消失，也就是不会关闭，难道只是关闭WEB？

按照设计是进程也关闭的，我记得中间有个commit后问题解决了，最新版的(release)我测试也未发现问题，你这个问题有什么触发条件吗

> 能不能增加选项，启动后不自动设置PAC，PAC设置可能对普通用户比较方便，但我觉得用浏览器扩展Proxy SwitchyOmega代替会更灵活。

可以考虑下个版本增加

> 好像不生成配置文件，每次重启都是默认配置，手工复制一份config.json.default改成config.json放到程序目录倒是可以解决

如果不修改配置就不会生成config.json，就是这样设计的。

> 2019-04-13 21:48:58 WARNING  tornado.access: 404 GET /configfile (127.0.0.1) 0.00ms

这个就奇怪了，0.6.1已经弃用了`/configfile`，不信你去看代码里都没有这个词，我怀疑你在用旧版的Web UI，建议Ctrl F5强制刷新或者清楚缓存

**Comment by miaomiaosoft** [comment]
确实是缓存导致的，WEB内容都是新版的但缓存却用的旧的还导致功能异常有点尴尬，清除缓存后问题都解决了，谢谢

**Comment by linsui** [comment]
支持不自动设置 PCA ，aria2 下载失败我找了好久原因才发现是因为自动设置了代理导致证书错误 :joy: 。如果不会很麻烦的话，可以考虑在第一次启动时弹出引导对话框，进行初始化设置。

**Comment by URenko** [comment]
引导对话框的话 @ws69 
配置文件或命令行参数是会弄一下的
