### ISSUE TITLE
端口冲突

### ISSUE THREAD

**Issue by linsui** [URenko/Accesser#26]
新版本非常好，谢谢你的付出 :smile: 。端口冲突的问题依然存在，而且现在无法直接解压。虽然可以通过配置文件和界面更改端口，但 webUI 的 7654 端口也和 I2P 冲突导致无法打开。所以希望可以增加修改 webUI 端口的选项。
不知道自动更改端口是否可以实现？不过端口冲突的情况应该并不多。

**Comment by URenko** [comment]
自动更改端口考虑到设置指南中的统一性，暂不实现。
