### ISSUE TITLE
针对可能存在后续添加网址目录的建议：A站（artstation）

### ISSUE THREAD

**Issue by huissv** [URenko/Accesser#28]
大大如果有添加其他网址的想法的话，强烈添加A站（CG视觉艺术作品网）：
https://www.artstation.com/
o(≧v≦)o~

其他网址测试打不开的（或被墙）：
https://vimeo.com/
https://www.amazon.co.jp/

**Comment by URenko** [comment]
artstation已支持，vimeo已修复，release在https://github.com/URenko/Accesser/releases/tag/beta
https://www.amazon.co.jp/ 在我这似乎没什么问题？请问是什么错误？
