### ISSUE TITLE
Please add *.fs.quoracdn.net domain to pac file

### ISSUE THREAD

**Issue by gomggx** [URenko/Accesser#29]
Please add *.fs.quoracdn.net domain to pac file

**Comment by URenko** [comment]
Can you provide a sample URL?

**Comment by gomggx** [comment]
https://qph.fs.quoracdn.net/main-thumb-t-20468-100-ydkwvplujqmhgkifcnrpaojmqcjnyyti.jpeg

**Comment by URenko** [comment]
It seems that it just has problem with DNS.
You can edit the _hosts_ file, add a line such as
`
151.101.189.2    qph.fs.quoracdn.net
`
or you can choose some DNS which can avoid pollution.

Even though it will work well if you add it to pac file, we will not add it as it is not SNI RST.

**Comment by gomggx** [comment]
I took your advice and modified my hosts file, and it works like a charm, thank you @URenko
