### ISSUE TITLE
……可以为小白解释一下需要安装证书的原因吗？

### ISSUE THREAD

**Issue by dzx-dzx** [URenko/Accesser#3]

**Comment by linsui** [comment]
@URenko 我有一个问题，从浏览器到 Accesser 之间使用 http 传输，是否可行? :confused:

**Comment by URenko** [comment]
我最初就是这样干的，但是这样要对所有传给浏览器的数据中的URL进行修改，试过发现不太行，而且编码后传输就更没办法。此外，还有HSTS强制浏览器不能降级到HTTP，如中文维基就有。

**Comment by linsui** [comment]
@URenko 果然不行啊 :joy:
