### ISSUE TITLE
0.6.1新版如何启动

### ISSUE THREAD

**Issue by P-256** [URenko/Accesser#30]
之前拷出来的方法不行了，运行start.bat后提示更新到最新版

**Comment by P-256** [comment]
另：bbc请fix ip
125.56.212.236	feeds.bbci.co.uk
52.31.189.25	search-suggest.api.bbci.co.uk
34.245.252.9	ess.api.bbci.co.uk

**Comment by URenko** [comment]
由于弃用7z改用Pyinstaller打包，无法直接提取
如果要非打包的话，请直接clone或下载代码仓库，对于Windows，还需[sysproxy.exe](https://github.com/Noisyfox/sysproxy)，可从旧版或v2rayN之类的复制

**Comment by P-256** [comment]
> 由于弃用7z改用Pyinstaller打包，无法直接提取
> 如果要非打包的话，请直接clone或下载代码仓库，对于Windows，还需[sysproxy.exe](https://github.com/Noisyfox/sysproxy)，可从旧版或v2rayN之类的复制

clone+sysproxy.exe没法启动，弹了一个窗之后没反应

**Comment by URenko** [comment]
你是在用老版的start.bat吗，那可能是同目录下没有Python的原因

**Comment by P-256** [comment]
@URenko ？我没有看懂。新版貌似没有start.bat

**Comment by URenko** [comment]
> @URenko ？我没有看懂。新版貌似没有start.bat

是的，你是要手动修改pac吗，如何启动的？

**Comment by P-256** [comment]
@URenko 是的

**Comment by URenko** [comment]
> @URenko 是的

如何启动的？
