### ISSUE TITLE
有没有能够在启动时不弹出控制台网页的方法？

### ISSUE THREAD

**Issue by lxfly2000** [URenko/Accesser#31]
首先感谢能提供这么方便的工具，我想实现开机自动启动，这个我可以自己改注册表或者在启动文件夹里建快捷方式，问题是启动时每次都会弹出控制台，因此还要手动关闭，有没有不弹出控制台的方法？还有这个程序没有系统托盘图标打开控制台输入网址不太方便，建议加个托盘图标，这样也能表示程序运行状态。

**Comment by miaomiaosoft** [comment]
手工编辑配置文件
  "webui": false,

你可以把WEBUI加入收藏夹，托盘是没什么存在意义的

**Comment by lxfly2000** [comment]
刚才在WIKI里看到了，谢谢
