### ISSUE TITLE
Cannot select DoH server on archlinux

### ISSUE THREAD

**Issue by maz-1** [URenko/Accesser#33]
error message:
```
Traceback (most recent call last):
  File "accesser.py", line 303, in <module>
    DoH.init().run_forever()
  File "/opt/Accesser/utils/DoH.py", line 136, in init
    logger.info('Auto selected DoH server: '+DoH_domain)
TypeError: can only concatenate str (not "NoneType") to str
```

I added 
```
    except Exception as e:
        print(e)
```
to line 113 of utils/DoH.py, And the exception info I get is
`The NPN extension requires OpenSSL 1.0.1 or later.`

According to a similar issue(https://github.com/HDE/aapns/issues/10), the openssl libray provided by system may not have npn support enabled

**Comment by URenko** [comment]
I‘ll check it when I have time, thanks

**Comment by lance6716** [comment]
Same TypeError here. Ubuntu 18

**Comment by URenko** [comment]
> Same TypeError here. Ubuntu 18

But I have just tested it on Ubuntu 18.04 (with python3.7.3 and Firefox) and it worked well.

You can check if the exception in line 113 is `The NPN extension requires OpenSSL 1.0.1 or later.`

**Comment by lance6716** [comment]
> > Same TypeError here. Ubuntu 18
> 
> But I have just tested it on Ubuntu 18.04 (with python3.7.3 and Firefox) and it worked well.
> 
> You can check if the exception in line 113 is `The NPN extension requires OpenSSL 1.0.1 or later.`

You're right. In fact openssl version is 1.1.1b, so it's same bug with maz-1

**Comment by URenko** [comment]
For the same reason as #10, it will not be fixed.

You can use dnscrypt-proxy temporarily.
