### ISSUE TITLE
自己添加域名保存后是立刻生效的吗

### ISSUE THREAD

**Issue by lxfly2000** [URenko/Accesser#35]
sorry我又来问了，我想在pac里添加其他域名，但不太清楚这个文件是修改后立刻生效还是重启后生效？还有pac是在temp文件夹里的，程序关闭后这个文件就没了，是不是需要每次启动都要手动修改？顺便想求测试一下gist.github.com能不能用你这个程序访问，谢谢

**Comment by URenko** [comment]
就服务器来说是立即生效，但是浏览器可能有缓存
因为添加域名的方案还没确定，故需要每次手动修改，不过既然要修改的话，建议直接用未打包的，参见 #30 ，这样就可以保存。

gist.github.com似乎只是DNS污染，虽然也能用这个程序访问，但修改hosts足矣
