### ISSUE TITLE
自动化

### ISSUE THREAD

**Issue by miaomiaosoft** [URenko/Accesser#36]
智能模式，WIN上只设置系统全局代理，像COW那样检测网站或IP是否被墙，就不用经常维护PAC列表了 （如果能调用WinDivert的话，可以直接修改流量，连代理都不用设）

有个开源程序zapret，可以用来直接访问被墙的HTTP网站，Accesser只适用HTTPS，加上这个就齐了
同时Accesser内可以设定一个下级翻墙代理，比如SS

首先，Accesser检测网站是否被重置或超时
没墙
  直接连接

被墙
  尝试使用Accesser或zapret连接
    还是无法连接，使用设定的SS连接

**Comment by URenko** [comment]
早有此意（没做便利的网站添加方式就是这个原因），就是太忙，有时间看看吧😂

**Comment by haohaoh4** [comment]
https://github.com/gfwlist/gfwlist

**Comment by URenko** [comment]
> https://github.com/gfwlist/gfwlist

但是gfwlist似乎不区分类型，另外，gfwlist的更新有点慢。。

**Comment by tec1987** [comment]
如果想自动化，要做的事情还有很多，目前accesser的优势主要是直连绕过SNI reset。
这样的话支持EDNS就比较关键，否则开一些有CDN的网站就很难保证速度。
需要搞一个对CDN友好的抗污染DNS代理，这样适配起来accesser才比较爽。

基本形成如下逻辑：
本地代理解析——连接测试
否则远程解析——连接测试
否则使用其它代理绕道访问

**Comment by songsammy** [comment]
不如考虑一下白名单？
https://github.com/felixonmars/dnsmasq-china-list

**Comment by URenko** [comment]
白名单可能因网站不支域前置而带来麻烦。
DNS的解决方案现阶段已经比较成熟，目前用的dnscrypt是其中一种比较成熟、标准的方法，且mozilla的测试表明对CDN影响不大（但不一定在大陆或其他DoH成立）。如果想用其他DNS解决方案，Accesser也有接口。

关键问题是区分SNI RST，特别是像中文维基这种还会丢包的

**Comment by lwb-2021** [comment]
试试clash-premium（这玩意不要钱）的script模式，可以用Python脚本试自动化处理，主要的问题是有没有什么可供解析的实时列表
