### ISSUE TITLE
Failed to execute script accessor

### ISSUE THREAD

**Issue by NineRiver7** [URenko/Accesser#38]

**Comment by URenko** [comment]
@NineRiver7 能发下Accesser.log吗

**Comment by NineRiver7** [comment]
链接：https://pan.baidu.com/s/1QJsV-fJz4C5Gpw3U_F_ViA 
提取码：hf9q 
复制这段内容后打开百度网盘手机App，操作更方便哦

干，QQ邮箱好像发不了文件




------------------ 原始邮件 ------------------
发件人: "URenko"<notifications@github.com>; 
发送时间: 2019年5月2日(星期四) 中午11:13
收件人: "URenko/Accesser"<Accesser@noreply.github.com>; 
抄送: "九河焦原血"<3061501732@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [URenko/Accesser] Failed to execute script accessor (#38)




@NineRiver7 能发下Accesser.log吗

**Comment by URenko** [comment]
你是导入失败后手动导入了证书吗

**Comment by NineRiver7** [comment]
对。




------------------ 原始邮件 ------------------
发件人: "URenko"<notifications@github.com>; 
发送时间: 2019年5月2日(星期四) 中午11:24
收件人: "URenko/Accesser"<Accesser@noreply.github.com>; 
抄送: "九河焦原血"<3061501732@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [URenko/Accesser] Failed to execute script accessor (#38)




你是导入失败后手动导入了证书吗

**Comment by URenko** [comment]
是不是参考了https://github.com/URenko/Accesser/wiki/FAQ#q-windows%E8%AE%BF%E9%97%AE%E7%9B%B8%E5%85%B3%E7%BD%91%E7%AB%99%E5%87%BA%E7%8E%B0%E8%AF%81%E4%B9%A6%E9%94%99%E8%AF%AF%E6%82%A8%E7%9A%84%E8%BF%9E%E6%8E%A5%E4%B8%8D%E6%98%AF%E7%A7%81%E5%AF%86%E8%BF%9E%E6%8E%A5neterr_cert_invalid%E4%B9%8B%E7%B1%BB%E7%9A%84%E6%80%8E%E4%B9%88%E5%8A%9E%E8%AF%81%E4%B9%A6%E5%AF%BC%E5%85%A5%E9%94%99%E8%AF%AF%E6%80%8E%E4%B9%88%E5%8A%9E%E5%A6%82%E4%BD%95%E5%8D%B8%E8%BD%BD%E8%AF%81%E4%B9%A6

**Comment by NineRiver7** [comment]
没有，我自己导入的证书。




------------------ 原始邮件 ------------------
发件人: "URenko"<notifications@github.com>; 
发送时间: 2019年5月2日(星期四) 中午11:27
收件人: "URenko/Accesser"<Accesser@noreply.github.com>; 
抄送: "九河焦原血"<3061501732@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [URenko/Accesser] Failed to execute script accessor (#38)




是不是参考了https://github.com/URenko/Accesser/wiki/FAQ#q-windows%E8%AE%BF%E9%97%AE%E7%9B%B8%E5%85%B3%E7%BD%91%E7%AB%99%E5%87%BA%E7%8E%B0%E8%AF%81%E4%B9%A6%E9%94%99%E8%AF%AF%E6%82%A8%E7%9A%84%E8%BF%9E%E6%8E%A5%E4%B8%8D%E6%98%AF%E7%A7%81%E5%AF%86%E8%BF%9E%E6%8E%A5neterr_cert_invalid%E4%B9%8B%E7%B1%BB%E7%9A%84%E6%80%8E%E4%B9%88%E5%8A%9E%E8%AF%81%E4%B9%A6%E5%AF%BC%E5%85%A5%E9%94%99%E8%AF%AF%E6%80%8E%E4%B9%88%E5%8A%9E%E5%A6%82%E4%BD%95%E5%8D%B8%E8%BD%BD%E8%AF%81%E4%B9%A6

**Comment by URenko** [comment]
那请问是如何操作的呢

**Comment by NineRiver7** [comment]
我直接把证书装入证书-受信任的证书发布机构里了，第一次操作，可能不太对




------------------ 原始邮件 ------------------
发件人: "URenko"<notifications@github.com>; 
发送时间: 2019年5月2日(星期四) 中午12:19
收件人: "URenko/Accesser"<Accesser@noreply.github.com>; 
抄送: "朝后清河"<3061501732@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [URenko/Accesser] Failed to execute script accessor (#38)




那请问是如何操作的呢

**Comment by URenko** [comment]
单单这样操作是不够的，另外，wiki中写的有bug😅，我待会改一改然后你再看看。
另外，证书导入失败这个问题真的难以捉摸。

**Comment by URenko** [comment]
> 单单这样操作是不够的，另外，wiki中写的有bug😅，我待会改一改然后你再看看。
> 另外，证书导入失败这个问题真的难以捉摸。

已更新，请浏览[wiki提供的方法](https://github.com/URenko/Accesser/wiki/FAQ#q-windows%E8%AE%BF%E9%97%AE%E7%9B%B8%E5%85%B3%E7%BD%91%E7%AB%99%E5%87%BA%E7%8E%B0%E8%AF%81%E4%B9%A6%E9%94%99%E8%AF%AF%E6%82%A8%E7%9A%84%E8%BF%9E%E6%8E%A5%E4%B8%8D%E6%98%AF%E7%A7%81%E5%AF%86%E8%BF%9E%E6%8E%A5neterr_cert_invalid%E4%B9%8B%E7%B1%BB%E7%9A%84%E6%80%8E%E4%B9%88%E5%8A%9E%E8%AF%81%E4%B9%A6%E5%AF%BC%E5%85%A5%E9%94%99%E8%AF%AF%E6%80%8E%E4%B9%88%E5%8A%9E%E5%A6%82%E4%BD%95%E5%8D%B8%E8%BD%BD%E8%AF%81%E4%B9%A6)，先卸载证书再导入证书。

**Comment by NineRiver7** [comment]
谢谢，但是问题是......我打不开控制界面，http://localhost:7654/显示“无法显示该网页”
 能直接告诉我路径吗？万分感谢！




------------------ 原始邮件 ------------------
发件人: "URenko"<notifications@github.com>; 
发送时间: 2019年5月2日(星期四) 中午12:45
收件人: "URenko/Accesser"<Accesser@noreply.github.com>; 
抄送: "朝后清河"<3061501732@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [URenko/Accesser] Failed to execute script accessor (#38)



 
单单这样操作是不够的，另外，wiki中写的有bug😅，我待会改一改然后你再看看。
另外，证书导入失败这个问题真的难以捉摸。
 
已更新，请浏览wiki提供的方法，先卸载证书再导入证书。

**Comment by URenko** [comment]
路径的话是在`%tmp%`（临时文件夹，可直接在地址栏或运行输入打开）下的某个_MEI开头的目录里。
打不开的原因可能是你还没有卸载之前安装的证书。

**Comment by NineRiver7** [comment]
还是失败



------------------ 原始邮件 ------------------
发件人: "URenko"<notifications@github.com>; 
发送时间: 2019年5月2日(星期四) 晚上9:31
收件人: "URenko/Accesser"<Accesser@noreply.github.com>; 
抄送: "朝后清河"<3061501732@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [URenko/Accesser] Failed to execute script accessor (#38)




路径的话是在%tmp%（临时文件夹，可直接在地址栏或运行输入打开）下的某个_MEI开头的目录里。
 打不开的原因可能是你还没有卸载之前安装的证书。

**Comment by NineRiver7** [comment]
更正了地址还是不行



------------------ 原始邮件 ------------------
发件人: "URenko"<notifications@github.com>; 
发送时间: 2019年5月2日(星期四) 晚上9:31
收件人: "URenko/Accesser"<Accesser@noreply.github.com>; 
抄送: "朝后清河"<3061501732@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [URenko/Accesser] Failed to execute script accessor (#38)




路径的话是在%tmp%（临时文件夹，可直接在地址栏或运行输入打开）下的某个_MEI开头的目录里。
 打不开的原因可能是你还没有卸载之前安装的证书。

**Comment by URenko** [comment]
`CertUtil -f -user -p "" -importPFX My root.pfx`执行失败还是网页打开失败?
手动导入前**个人>证书**和**受信任的根证书颁发机构>证书**这两个条目下的Accesser字样证书是否清除干净。
另外最好启动前注意下任务管理器中有无多余的accesser.exe进程

**Comment by NineRiver7** [comment]
CertUtil： -importPFX 失败：0x80070057（win32：87）CertUtil：参数错误




------------------ 原始邮件 ------------------
发件人: "URenko"<notifications@github.com>; 
发送时间: 2019年5月3日(星期五) 晚上6:26
收件人: "URenko/Accesser"<Accesser@noreply.github.com>; 
抄送: "朝后清河"<3061501732@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [URenko/Accesser] Failed to execute script accessor (#38)




CertUtil -f -user -p "" -importPFX My root.pfx执行失败还是网页打开失败?
 手动导入前个人>证书和受信任的根证书颁发机构>证书这两个条目下的Accesser字样证书是否清除干净。
 另外最好启动前注意下任务管理器中有无多余的accesser.exe进程

**Comment by URenko** [comment]
看来 #12 的问题终于复现了，不过也不太一样，原因未知。能说下你的Windows版本吗？可能会有帮助。

暂时的解决方法就是不用一键程序，可以参考[开发者指南](https://github.com/URenko/Accesser/wiki/开发者指南)进行配置，或者解压老版本(v0.6.0)使用

启动方法就是`python3 accesser.py`

**Comment by NineRiver7** [comment]
WINDOWS7
内部版本7601

**Comment by URenko** [comment]
计划下个版本增加个不自动导入Windows证书储存区的选项以解决此类问题（代价是便携性降低）。

**Comment by URenko** [comment]
[新版本](https://github.com/URenko/Accesser/releases/tag/v0.6.2)已支持不自动导入Windows证书储存区。
可使用命令行参数`--notimportca`或`config.json`中的`importca`选项（详见[设置说明](https://github.com/URenko/Accesser/wiki/设置说明)）来阻止自动导入证书，然后手动信任根证书（可参考[这里](https://www.cnblogs.com/lisa090818/p/4276031.html)），位于`CERT/root.crt`。

**Comment by mrhso** [comment]
这个问题的根源其实是……
![image](https://user-images.githubusercontent.com/13294467/179328860-46ccfba2-c6f0-497d-b4c5-20a109a8b0fe.png)
Windows 7 的 `CertUtil -importPFX` 并没有 `CertificateStoreName` 这个参数，但是 `CertUtil -exportPFX` 倒是有。
只是根据帮助的「默认为个人计算机存储」来看，其实本来就是存到 My 去的，也就是说这个 `My` 完全是多余的。

**Comment by URenko** [comment]
感谢指出~
