### ISSUE TITLE
老大告诉我  在Termux安装到底要先装什么？

### ISSUE THREAD

**Issue by cok3307788** [URenko/Accesser#41]
(骁龙625)aarch64 , Android7.1.2 ,Termux 65 , Python3.7

clone完毕，从python acceseer.py开始
tornado
tld
dns
openssl
cffi
cryptography
。。。。
个个都 no found，疯狂报错
好不容易不说module no found了，给我整个报错如下
`Traceback (most recent call last):
  File "accesser.py", line 36, in <module>
    from utils import certmanager as cm
  File "/data/data/com.termux/files/home/Accesser/utils/certmanager.py", line 25, in <module>
    from .setting import basepath                            File "/data/data/com.termux/files/home/Accesser/utils/setting.py", line 12, in <module>                                 config = json.load(f)
  File "/data/data/com.termux/files/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/data/data/com.termux/files/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)                        File "/data/data/com.termux/files/usr/lib/python3.7/json/decoder.py", line 337, in decode                               obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/data/com.termux/files/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 3 column 16 (char 28)
`

**Comment by URenko** [comment]
Termux没有测试过，看起来是对json中第三行`null`的解析错误，不太清楚原因，尝试将`null`改为`""`或`0`可能行。

**Comment by cok3307788** [comment]
之前我看wiki，就把第三行值改成了Accesser.log，改回null后可以启动，但新错误紧随而来
'Accesser v0.6.1  Copyright (C) 2018-2019  URenko           2019-05-10 00:34:36 INFO     Accesser.DoH: Selecting DoH server...                                                    2019-05-10 00:34:37 INFO     Accesser: server started at 127.0.0.1:7655
Traceback (most recent call last):
  File "accesser.py", line 303, in <module>
    DoH.init().run_forever()
  File "/data/data/com.termux/files/home/Accesser/utils/DoH.py", line 135, in init                                        logger.info('Auto selected DoH server: '+DoH_domain)
TypeError: can only concatenate str (not "NoneType") to str^CException ignored in: <module 'threading' from '/data/data/com.termux/files/usr/lib/python3.7/threading.py'>
Traceback (most recent call last):                           File "/data/data/com.termux/files/usr/lib/python3.7/threading.py", line 1281, in _shutdown
    t.join()                                                 File "/data/data/com.termux/files/usr/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()                             File "/data/data/com.termux/files/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock                  elif lock.acquire(block, timeout):                     KeyboardInterrupt'

**Comment by URenko** [comment]
可以尝试注释掉DoH.py的133-139行，好像所有的DoH测试都失败了？可能后面还是会有问题。

DoH.py已不再维护(#10)，dev分支中使用了[dnscrypt-proxy](https://github.com/jedisct1/dnscrypt-proxy/releases)，他们有在Termux上测试过，把Android版的编译好的dnscrypt-proxy放在dnscrypt目录下应该就行。

另外建议加`--cli`参数以不自动打开Web UI。

**Comment by cok3307788** [comment]
注释掉没有解决问题，话说应该是133-138行吧。。
我没有看到dnscrypt的目录啊，具体是在哪里呢？

**Comment by URenko** [comment]
> 注释掉没有解决问题，话说应该是133-138行吧。。

抱歉，是133-138行，估计是看的是不同时间提交的代码。

> 我没有看到dnscrypt的目录啊，具体是在哪里呢？

还在dev分支，建议使用 e75e6a37407870db980e894f1e759e47b531b6b8 这个点（后面可能会有些不稳定的更改）。

**Comment by cok3307788** [comment]
谢谢老大，可以正常运行了，可以在wiki里增加Termux的用例啦。PS：要是能提供一个不在Bash上打印日志的选项就更好了😀

**Comment by URenko** [comment]
@cok3307788 你是注释DoH.py部分代码还是用dev分支？

json第三行（也就是`"logfile"`）指定为一日志文件路径就不会在Bash上打印日志，详见wiki。

**Comment by cok3307788** [comment]
注释无用（会报错nonetype error），用的是Dev分支，放入dnscrypt-proxy的方法
