### ISSUE TITLE
极大的log文件产生

### ISSUE THREAD

**Issue by duren13** [URenko/Accesser#43]
使用几小时后产生了21GB的log文件且还在不断增加.
OS: windows 8.1
浏览器: firefox 66.0.5
日志级别: debug

**Comment by cok3307788** [comment]
http://localhost:7654/里面，把日志级别设置成Critical，不崩溃都不会打日志

**Comment by URenko** [comment]
@duren13 21GB ( ☉д⊙)，这有点夸张啊，能发下部分的日志文件内容吗（如果还在的话）。

调整日志级别或者直接不设日志文件路径都能解决问题，详见wiki。

**Comment by duren13** [comment]
文件太大即使notepad++也打不开,日志级别已调,只是好奇究竟怎样才会产生如此大的日志文件
