### ISSUE TITLE
English language?

### ISSUE THREAD

**Issue by Bizarrus** [URenko/Accesser#44]
Please provide an english language...!

**Comment by URenko** [comment]
We are busy now and this project is mainly for Chinese, so it may take a long time.

And we welcome PR :)

**Comment by Bizarrus** [comment]
I cant create PR, because i can't speak chinese ;)

**Comment by funnypro** [comment]
非中国大陆地区也有人需要用吗？

**Comment by Bizarrus** [comment]
close this shit. bye.

**Comment by URenko** [comment]
- Firstly, SNI RST not only exists on the main land of China.
- Secondly, English version is still in plan, including README and the webui (but the priority is not high, technology the first).
- Thirdly, keep calm.
- Finally, we still welcome PR.

**Comment by funnypro** [comment]
似乎是我说的话有问题？

只是不太理解除了大陆之外还会有其他地方出现这个问题？

**Comment by funnypro** [comment]
或者说：除了大陆之外，其他地方墙也很高？

**Comment by URenko** [comment]
@funnypro 实际上，SNI RST在其他国家也存在（如韩国，参考 https://zh.wikipedia.org/zh-hans/韩国网络审查 ），至于墙的“高”，应该没有大陆那么“高”。除此之外，SNI RST很早就被用于组织的网络管控（如企业、学校）。当然，本项目默认是按大陆的普遍网络环境配置的。

**Comment by funnypro** [comment]
> @funnypro 实际上，SNI RST在其他国家也存在（如韩国，参考 [https://zh.wikipedia.org/zh-hans/韩国网络审查](https://zh.wikipedia.org/zh-hans/%E9%9F%A9%E5%9B%BD%E7%BD%91%E7%BB%9C%E5%AE%A1%E6%9F%A5) ），至于墙的“高”，应该没有大陆那么“高”。除此之外，SNI RST很早就被用于组织的网络管控（如企业、学校）。当然，本项目默认是按大陆的普遍网络环境配置的。

明白了，不过看起来那个机械翻译可能实际意思出了偏差？

**Comment by URenko** [comment]
> 明白了，不过看起来那个机械翻译可能实际意思出了偏差？

`¯\_(ツ)_/¯`不知道，至少我感觉没有。

**Comment by funnypro** [comment]
> > 明白了，不过看起来那个机械翻译可能实际意思出了偏差？
> 
> `¯\_(ツ)_/¯`不知道，至少我感觉没有。

不过感觉那位好像很气愤欸？

**Comment by URenko** [comment]
There may be some misunderstandings...
