### ISSUE TITLE
OneDrive网页版以及ipv6的问题

### ISSUE THREAD

**Issue by chaoscard** [URenko/Accesser#46]
网络运营商:CNGI-CERNET2-AS-AP China Next Generation Internet CERNET2 属于教育网
浏览器：chrome 74.0.3729.169（正式版本） （64 位）

OneDrive网页版能打开，但是看不到文件
![捕获](https://user-images.githubusercontent.com/50175182/58848963-0c026280-86bb-11e9-8e92-2b4f2d2bbd12.PNG)

关闭对ipv6的支持：现在公网ipv6没有任何用，开启也不能上谷歌，教育网ipv6还尚可苟延残喘，但是开了Accesser后反而打不开谷歌，油管了。

**Comment by URenko** [comment]
IPv6目前尚在试验，似乎也有些可用的( #42 )，不过默认不开启应该对一般用户没什么影响。
谷歌这个本来是为Google reCAPTCHA设计的，但是由于PAC只能在域名级别筛选所以全都影响到，不过之前测试似乎也有成功过（不太记得了）。

**Comment by chaoscard** [comment]
> IPv6目前尚在试验，似乎也有些可用的( #42 )，不过默认不开启应该对一般用户没什么影响。
> 谷歌这个本来是为Google reCAPTCHA设计的，但是由于PAC只能在域名级别筛选所以全都影响到，不过之前测试似乎也有成功过（不太记得了）。

OneDrive网页版只是我有问题吗？

**Comment by URenko** [comment]
> OneDrive网页版只是我有问题吗？

不，刚刚那个commit就是针对这个问题的

**Comment by dblark** [comment]
但是对于我来说 OneDrive网页版还是看不到文件呢……

是修改后没用吗？

**Comment by URenko** [comment]
> 但是对于我来说 OneDrive网页版还是看不到文件呢……
> 是修改后没用吗？

请问你是直接下载exe还是用代码呢，如果是前者的话是因为修改尚未部署到exe

**Comment by dblark** [comment]
> > 但是对于我来说 OneDrive网页版还是看不到文件呢……
> > 是修改后没用吗？
> 
> 请问你是直接下载exe还是用代码呢，如果是前者的话是因为修改尚未部署到exe

我用的是 exe……原来是这样，好的我用源代码试一下

**Comment by URenko** [comment]
stale
