### ISSUE TITLE
或许是一个新用途

### ISSUE THREAD

**Issue by songsammy** [URenko/Accesser#52]
在**的一家**酒店，服务还不错，只是wifi需要手机号码登陆
![Screenshot_2019-07-07 天翼高清](https://user-images.githubusercontent.com/30046778/60768248-73b23000-a0f5-11e9-8166-d1ca4fa6fbee.png)
通过此程序，好像可以绕过那个验证
只是需要手动添加域名。
http://61.160.149.38:8050
http://61.160.149.38:8050/etv/model/index.html?gw_address=192.168.10.254&gw_port=2060&gw_id=C88F267127AF&client_mac=68:94:23:f3:c6:3b&url=http%3A//www.jb51.net/&ssid=aWiFi-Free
ps：不知道为什么awifi

**Comment by songsammy** [comment]
ETV无线网络使用须知：
	尊敬的客户，您好：
	欢迎您入住本酒店！
	我们竭诚为您提供免费优质的互联网无线网络接入环境。您在连接上网前，请认真阅读此使用须知（以下简称“须知”），只有当您已充分阅读、理解并点击同意接受须知的全部内容后，方可按照网络认证页面提示填写信息并完成全部实名认证程序后，享受本酒店提供的免费无线上网服务。如果您不同意须知中任何条款内容，您应立即停止使用无线上网服务。若您是18周岁以下的未成年人，请在法定监护人的陪同下阅读本须知。
	一、    根据《互联网安全保护技术措施规定》（公安部令第82号）要求，您在使用本服务的过程中，需要提供一些必要的个人信息资料，并根据公安、国安、检察院等有关机关要求向其提供，例如：您需要提供手机号码并获取验证码信息进行实名身份认证等。若您不提供、提供的信息不完整或不真实的，则无法使用本服务或在使用过程中受到限制。
	二、    您在使用无线网络时不得利用本服务从事以下行为：
	1、 发布、传送、传播、储存违反国家法律、危害国家安全统一、社会稳定、公序良俗、社会公德以及侮辱、诽谤、淫秽、暴力的内容。
	2、 发布、传送、传播、储存侵害他人名誉权、肖像权、知识产权、商业秘密等合法权利的内容。
	3、 虚构事实、隐瞒真相以误导、欺骗他人。
	4、发表、传送、传播广告信息及垃圾信息。
	5、从事其他违反法律法规、政策及公序良俗、社会公德等的行为。
	三、    本服务可能会受各种安全问题的侵扰（您下载安装的其他软件或访问的其他网站中可能含有病毒、木马程序或其他恶意程序以及黑客攻击等，威胁您的移动终端设备和数据的安全，继而影响本服务的正常使用；您选择与服务不相匹配的终端操作系统、浏览器导致了任何问题或损害等）。因此，您应加强信息安全及个人信息的保护意识，注意密码保护，以免遭受损失。本酒店不承担任何由此产生的一切法律责任。
	四、    本酒店将根据国家法律法规变化及维护上网安全需要，及时完善本须知，并在服务页面下方位置展现，您可以点击查阅最新版本的须知。须知内容变更后，如果您继续使用无线上网服务，即视为您已接受变更后的须知内容。如果您不接受变更后的须知内容，您应立即停止使用无线上网服务。
	五、    作为互联网上网服务的提供者，本酒店认真贯彻落实国家法律、法规要求的互联网安全保护技术措施，并且接受公安机关公共信息网络安全监察部门对互联网安全保护技术措施落实情况的监督管理。

**Comment by songsammy** [comment]
具体原理我不太懂，但是启动exe前，所有网页都会被跳转到上述URL。
启动后，至少可以访问https页面
再搭配一个https everywhere,就无敌了。

**Comment by URenko** [comment]
原理应该就类似那种公司、学校的网络限制，通过SNI来识别，但是其实这个方法不怎么通用，有些网络验证是拦截全部流量的。
另外，启动exe前连加https的维基百科也会跳转到验证页面吗？（因为有HSTS，理论上不允许降级的）

**Comment by songsammy** [comment]
是的，所有都会跳转。

**Comment by louiesun** [comment]
> 原理应该就类似那种公司、学校的网络限制，通过SNI来识别，但是其实这个方法不怎么通用，有些网络验证是拦截全部流量的。 另外，启动exe前连加https的维基百科也会跳转到验证页面吗？（因为有HSTS，理论上不允许降级的）

我们学校是乱发RST，当时吓得我以为是gfw发威了。
