### ISSUE TITLE
安卓不断弹该站点的证书不被信任。 且如何实现全局代理

### ISSUE THREAD

**Issue by HeiLAAS** [URenko/Accesser#55]
安卓9
比如进入reddit的时候，弹了无数个证书不信任。
已经导入了CRET文件夹里面的2个证书

**Comment by URenko** [comment]
浏览器不一定用系统的证书库，换个浏览器试试，最好是系统自己的

**Comment by uicba** [comment]
> 电脑开热点。确保电脑上可使用后，设置Android的PAC代理为http://电脑的局域网IP:7654/pac，右键导出证书另存为后，在Android中导入信任即可。

为什么浏览器打不开电脑的局域网IP呢？除了http://localhost:7654/pac/

**Comment by uicba** [comment]
电脑除了本地地址localhost外，有局域网地址吗？

**Comment by URenko** [comment]
> 电脑除了本地地址localhost外，有局域网地址吗？

比如你连了个无线路由，那么电脑在其中的IP可能是192.168.1.102这种
又比如你用电脑开了个热点，电脑的IP可能是192.168.137.1这种
其他的还有学校、企业等的局域网
可以ipconfig或者在网络属性查看

**Comment by uicba** [comment]
@URenko 电脑浏览器打不开

**Comment by uicba** [comment]
![Snipaste_2019-08-18_21-16-30](https://user-images.githubusercontent.com/54227194/63224902-898b3880-c1fd-11e9-975b-fe114034b792.png)
![Snipaste_2019-08-18_21-14-46](https://user-images.githubusercontent.com/54227194/63224908-9c9e0880-c1fd-11e9-84d0-f02283fd8bf7.png)

**Comment by uicba** [comment]
@URenko Accesser有bug吗？怎么无法访问电脑的局域网IP？

**Comment by URenko** [comment]
@uciba webui.py的94行`127.0.0.1`改为`0.0.0.0`，这是一个bug，以前居然没有发现，感谢反馈

**Comment by uicba** [comment]
@URenko 我不会操作

**Comment by uicba** [comment]
@URenko 我是说我不会编译

**Comment by URenko** [comment]
抱歉，最近比较忙，加标签是为了提醒

https://github.com/URenko/Accesser/releases/tag/v0.6.3-dev.0 已修改，改为局域网后在同目录下放一份PAC，如可以在 https://github.com/URenko/Accesser/blob/v0.6.3-dev.0/template/pac 的基础上，`var proxy = "PROXY 127.0.0.1:{{port}};";` 改为 `PROXY "电脑在局域网中的IP:服务器端口(默认为7655);";`

**Comment by uicba** [comment]
@URenko 你忘记加临时镜像了

**Comment by uicba** [comment]
`电脑在局域网中的IP:7655`依旧不能访问，你确定上传新版本了吗？
![image](https://user-images.githubusercontent.com/54227194/64471551-c48de580-d185-11e9-8471-2d9f4cc71bae.png)
![image](https://user-images.githubusercontent.com/54227194/64471589-23ebf580-d186-11e9-9911-56125089d29b.png)

**Comment by URenko** [comment]
> @URenko 你忘记加临时镜像了

pre-release就不加了


> `电脑在局域网中的IP:7655`依旧不能访问，你确定上传新版本了吗

默认网页端口是7654

**Comment by uicba** [comment]
> 默认网页端口是7654

照你这么说，服务器端口的设置是个摆设？
![image](https://user-images.githubusercontent.com/54227194/64476008-4436a700-d1bc-11e9-876e-222be020c07d.png)

**Comment by uicba** [comment]
![image](https://user-images.githubusercontent.com/54227194/64476296-962cfc00-d1bf-11e9-8ad1-eaef9fa6bae0.png)

**Comment by URenko** [comment]
> 照你这么说，服务器端口的设置是个摆设？

服务器端口和WebUI端口是两个不同的，请仔细阅读https://github.com/URenko/Accesser/wiki/%E8%AE%BE%E7%BD%AE%E8%AF%B4%E6%98%8E

**Comment by uicba** [comment]
> 尝试设置代理（手动）为192.168.137.1，端口7655，测试后记得改回去

不行

**Comment by URenko** [comment]
stale
