### ISSUE TITLE
Accesser会使Google安全搜索(SafeSearch)强制打开且不能关闭

### ISSUE THREAD

**Issue by uicba** [URenko/Accesser#56]
![Snipaste_2019-08-18_08-08-01](https://user-images.githubusercontent.com/54227194/63406070-545c3180-c41b-11e9-99e7-376646173c77.png)
![Snipaste_2019-08-18_08-06-22](https://user-images.githubusercontent.com/54227194/63406069-545c3180-c41b-11e9-9121-2c993afbdb20.png)

**Comment by URenko** [comment]
IPv6?

**Comment by uicba** [comment]
> IPv6?

不是

**Comment by uicba** [comment]
翻墙了，IP地址是境外的。

**Comment by uicba** [comment]
翻墙软件和Accesser同时打开了

**Comment by URenko** [comment]
通过修改PAC？

**Comment by uicba** [comment]
> 通过修改PAC？

默认的PAC，从未改动。

**Comment by uicba** [comment]
@URenko

**Comment by URenko** [comment]
@uicba 那你是如何上google的呢？

**Comment by uicba** [comment]
> @uicba 那你是如何上google的呢？是可用的IPv4的IP吗

我在上面不是说了嘛，翻墙软件和Accesser同时打开了。
翻墙软件是SSTAP。

**Comment by URenko** [comment]
首先，同时使用SSTAP和Accesser并不好，制作PAC(但是SSTAP好像不是/没有用PAC)使两者兼容才是正确方式；
其次，这个应该不是Accesser的问题，应该与你的代理服务提供方或是你的google使用方式有关。

**Comment by uicba** [comment]
@URenko 
不，和Accesser有关系，我关闭代理脚本，Google安全搜索也就跟着关闭了。
![image](https://user-images.githubusercontent.com/54227194/64471371-8d1e3980-d183-11e9-886e-3a77ba2a2ba9.png)

**Comment by URenko** [comment]
Accesser和google在http层次上有关的只有config.json里的`http_redirect`下的`"www.google.com/recaptcha/": "www.recaptcha.net/recaptcha/",`可以尝试删掉该行

再不行把PAC里的google删掉，但是这些都不应与安全搜索有关

不用SSTAP，不便测试
