### ISSUE TITLE
Import Failed

### ISSUE THREAD

**Issue by ChangITP** [URenko/Accesser#62]
这是log文件
[Accesser.log](https://github.com/URenko/Accesser/files/3734434/Accesser.log)
之前用着好好的，今天突然不管用了，证书导入失败。
而且我在**个人**与**受信任的根证书颁发机构**下面都找不到Accesser的证书。
在cmd里尝试手动导入证书（CertUtil -f -user -p "" -importPFX My root.pfx），提示 CertUtil 参数错误
![image](https://user-images.githubusercontent.com/33488875/66970512-6aefd380-f0c0-11e9-8b6e-508f10b6b9b9.png)

请问这该怎么办呢？

**Comment by URenko** [comment]
你可以尝试用证书管理器[手动导入信任证书](https://github.com/URenko/Accesser/wiki/FAQ#q-windows%E8%AE%BF%E9%97%AE%E7%9B%B8%E5%85%B3%E7%BD%91%E7%AB%99%E5%87%BA%E7%8E%B0%E8%AF%81%E4%B9%A6%E9%94%99%E8%AF%AF%E6%82%A8%E7%9A%84%E8%BF%9E%E6%8E%A5%E4%B8%8D%E6%98%AF%E7%A7%81%E5%AF%86%E8%BF%9E%E6%8E%A5neterr_cert_invalid%E4%B9%8B%E7%B1%BB%E7%9A%84%E6%80%8E%E4%B9%88%E5%8A%9E%E8%AF%81%E4%B9%A6%E5%AF%BC%E5%85%A5%E9%94%99%E8%AF%AF%E6%80%8E%E4%B9%88%E5%8A%9E%E5%A6%82%E4%BD%95%E5%8D%B8%E8%BD%BD%E8%AF%81%E4%B9%A6)
