### ISSUE TITLE
nyaa.si

### ISSUE THREAD

**Issue by RtYkk** [URenko/Accesser#64]
昨天开始nyaa.si的dns国内解析开始出现大量问题
http://ping.chinaz.com/nyaa.si
尝试输入上述“海外”得到的一个俄罗斯IP进入hosts未能解决无法访问问题，这次这么直接？会不会也多了一层dns阻断……

**Comment by miaomiaosoft** [comment]
应该和Accesser的处理方式有关，服务器不接受这种方式访问，一般用了CF或亚马逊服务器的黑名单网站容易这样
https://github.com/URenko/Accesser/issues/12  这个反馈里有提到
