### ISSUE TITLE
在 Android 上使用

### ISSUE THREAD

**Issue by jslll135** [URenko/Accesser#65]
目前 Wiki 中建议参考 https://github.com/URenko/Accesser/issues/41 在 Termux 中运行 Accesser 。虽然这个过程并不复杂，但这个 issue 中的说明有些不清楚，对于没有任何经验的用户（比如我）而言有困难。因此我将完整的步骤分享在这里，希望可以帮助其他人。

安装 Termux 后，在 home 目录运行以下命令。注意如果在内部存储运行由于文件系统的问题可能无法运行。

```
sed -i 's@^\(deb.*stable main\)$@#\1\ndeb https://mirrors.tuna.tsinghua.edu.cn/termux stable main@' $PREFIX/etc/apt/sources.list
apt update && apt upgrade
pkg install clang python git wget unzip
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pip -U
pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
pip install cffi tornado tld dnspython pyopenssl
git clone https://github.com/URenko/Accesser.git
cd ./Accesser/
wget -O dnscrypt-proxy.zip -c https://github.com/DNSCrypt/dnscrypt-proxy/releases/download/2.0.31/dnscrypt-proxy-android_arm64-2.0.31.zip
unzip -j -d ./dnscrypt ./dnscrypt-proxy.zip */dnscrypt-proxy
rm ./dnscrypt-proxy.zip
python accesser.py
```

为了便于国内使用我使用了清华的镜像，但根据帮助页面的说明，这个镜像可能会导致一些问题。请参考 https://mirror.tuna.tsinghua.edu.cn/help/termux/

另外请问是否可以打包二进制文件？我没有成功，如果可以对用户而言就更加方便了。

**Comment by jslll135** [comment]
更进一步，如果您可以维护一份安装脚本，则可以通过类似 v2ray 的方式使用一行命令安装并保持更新。

**Comment by URenko** [comment]
首先感谢您的分享，已将该issue加入wiki。但是我近期（大概长期也是）并没有太多时间投入于此，所以仅制作了WIndows平台的二进制文件，没有其他平台的计划。
