### ISSUE TITLE
请求添加*.githubusercontent.com

### ISSUE THREAD

**Issue by YuxuanZuo** [URenko/Accesser#76]
最近githubusercontent及其子域名部分地区已被SNI RST，GitHub的代码以及头像的加载经常时断时续，希望可以添加~

**Comment by YuxuanZuo** [comment]
同样也希望添加gist.github.com，这个域名被dns污染。
有一个想法，是否可以将软件的代理规则独立到accesser.exe的外部，让用户自己手动修改？

**Comment by SeaHOH** [comment]
应该不是 SNI RST 吧，敢？？请晒出抓包数据。

**Comment by YuxuanZuo** [comment]
@SeaHOH ![批注 2020-03-02 185513](https://user-images.githubusercontent.com/35165992/75670313-75012000-5cb7-11ea-90c2-097a49c30e49.png)
![批注 2020-03-02 185513-1](https://user-images.githubusercontent.com/35165992/75670401-9f52dd80-5cb7-11ea-8b8e-264780ecd589.png)

**Comment by YuxuanZuo** [comment]
@SeaHOH 准确的来说应该是时断时续，经常被干扰，中国移动网络环境下部分地区还有dns污染

**Comment by SeaHOH** [comment]
> 时断时续，经常被干扰

这不是 SNI RST，DNS 污染和连接丢包请使用其它办法解决。
