### ISSUE TITLE
请求支持protonmail.com

### ISSUE THREAD

**Issue by songsammy** [URenko/Accesser#77]
我试图访问protonmail.com，但被墙了。
您的连接不是私密连接
攻击者可能会试图从 protonmail.ch 窃取您的信息（例如：密码、通讯内容或信用卡信息）。了解详情
NET::ERR_CERT_AUTHORITY_INVALID
NET::ERR_CERT_AUTHORITY_INVALID
Subject: Accesser_Proxy

Issuer: Accesser

Expires on: 2021年3月4日

Current date: 2020年3月4日

PEM encoded chain:
-----BEGIN CERTIFICATE-----
MIIEATCCAemgAwIBAgIIWOpaTqy9VAAwDQYJKoZIhvcNAQELBQAwJjERMA8GA1UE
AwwIQWNjZXNzZXIxETAPBgNVBAoMCEFjY2Vzc2VyMB4XDTIwMDMwNDExMTc0OVoX
DTIxMDMwNDExMjc0OVowLDEXMBUGA1UEAwwOQWNjZXNzZXJfUHJveHkxETAPBgNV
BAoMCEFjY2Vzc2VyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA70xc
dQDTRA/TpaGj0oKswL0Z8famWmD0

**Comment by URenko** [comment]
你是已经用了Accesser? 此外protonmail.com似乎已被路由黑洞

**Comment by ygsk10** [comment]
1. 从日志看起来你的浏览器没有信任Aceesser的证书。
2. 如果用pac，请在template/pac加入protonmail.ch
3. 如果网站不支持Accesser会无响应

**Comment by ygsk10** [comment]
1. 去导入证书(删了一次证书不导入就复现了)
2. 如果用pac，请在template/pac加入protonmail.ch
3. 如果网站不支持Accesser, 应该是无响应或者reset 
<details><summary>截图</summary> <img src= "https://user-images.githubusercontent.com/60314251/77911938-33956d80-7281-11ea-81f9-476d536c163b.png" alt="Screenshot_20200330-115850_Fennec_F-Droid"> </img>
</details>

**Comment by URenko** [comment]
如果用了Accesser，无响应一般意味着IP被屏蔽或者浏览器到Accesser之间有问题而不是网站不支持。
用Accesser能连上并不意味着网站一定被SNI RST，可能是连接所用的IP不同（因为Accesser使用自己的DNS）

**Comment by URenko** [comment]
stale
