### ISSUE TITLE
访问P站提示ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by lxfly2000** [URenko/Accesser#80]
已经持续两天了

**Comment by NingMeiWang** [comment]
最近我也是这样，

**Comment by LCinHK** [comment]
+1, firefox显示了和访问nikkei一样的错误，
python输出
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1076)

**Comment by young233-cyber** [comment]
仍然有问题。。。作者加油

**Comment by URenko** [comment]
看起来是DNS的锅？解析到疑似为pixiv的Cloudflare节点（`104.18.12.135`），修改`dnscrypt/cloaking-rules.txt`使用`210.140.131.203`的IP似乎可行。
Cloudflare的话会有 #19 的问题

虽然看起来目前修改配置文件就能解决，但是鉴于打算做一些修改，暂不更改（持续咕咕咕中）

**Comment by ASC8384** [comment]
> 
> 
> 看起来是DNS的锅？解析到疑似为pixiv的Cloudflare节点（`104.18.12.135`），修改`dnscrypt/cloaking-rules.txt`使用`210.140.131.203`的IP似乎可行。
> Cloudflare的话会有 #19 的问题
> 
> 虽然看起来目前修改配置文件就能解决，但是鉴于打算做一些修改，暂不更改（持续咕咕咕中）

修改后无效。
```bash
λ ping 104.18.12.135

正在 Ping 104.18.12.135 具有 32 字节的数据:
来自 104.18.12.135 的回复: 字节=32 时间=136ms TTL=46
请求超时。
来自 104.18.12.135 的回复: 字节=32 时间=132ms TTL=46
请求超时。

104.18.12.135 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 2，丢失 = 2 (50% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 132ms，最长 = 136ms，平均 = 134ms

λ ping pixiv.net

正在 Ping pixiv.net [210.140.131.219] 具有 32 字节的数据:
来自 210.140.131.219 的回复: 字节=32 时间=125ms TTL=41
来自 210.140.131.219 的回复: 字节=32 时间=125ms TTL=41
来自 210.140.131.219 的回复: 字节=32 时间=124ms TTL=41
来自 210.140.131.219 的回复: 字节=32 时间=125ms TTL=41

210.140.131.219 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 124ms，最长 = 125ms，平均 = 124ms
```
但是修改后无效，显示
```
WARNING  Accesser: Try connect www.pixiv.net with 104.18.12.135 timeout.
```

**Comment by hoochanlon** [comment]
这个问题和证书脚本程序的执行与P站[内容安全策略CSP](https://developer.mozilla.org/zh-CN/docs/Web/Security/CSP)的定制有关，墙对站点的限制等级就另说了。
现在多数站点采用[SNI](https://zh.wikipedia.org/wiki/%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%90%8D%E7%A7%B0%E6%8C%87%E7%A4%BA)，一个CDN ip对应多个域名，仅靠ip地址访问也是没太大意义的。

不过，你挺有心的 :+1:，顺便也将你的程序使用收录到我的著作中。(*^_^*)

**Comment by URenko** [comment]
@ASC8384 至少从我这里的测试来看是可用的，你的连接问题可能是丢包过多（从ping来看），可尝试换个IP（还有很多）

@hoochanlon 看起来CSP只涉及HTTP及往上层，与TLS及其下层无关，不太理解的你的第一句话（如有我不了解的地方还请给出详细说明）。
虽然这里的方法对于CDN无用（尤其是Cloudflare），但从实践的结果看效果不错。
最后感谢你的收录。

**Comment by hoochanlon** [comment]
第一句说的是资源加载限制的问题，`object-src 'none'; `即不加载任何资源，启用后，不符CSP条件的外部资源就会被阻止加载。第二句才是说连接问题。
![piv](https://user-images.githubusercontent.com/35732922/79178337-8fdabe80-7e37-11ea-80be-7cd0be7045c5.png)

**Comment by URenko** [comment]
@hoochanlon 可能是你/我误会了，你说的这个和本issue的问题不是同一个问题

**Comment by hoochanlon** [comment]
确实

获取 Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by ASC8384** [comment]
> 
> 
> @ASC8384 至少从我这里的测试来看是可用的，你的连接问题可能是丢包过多（从ping来看），可尝试换个IP（还有很多）

我在`hosts`和`dnscrypt/cloaking-rules.txt`里手动添加了新的解析（210.140.131.219），但在日志里依旧是旧的IP（104.18.12.135）。

而且`dnscrypt/cloaking-rules.txt`里并没有发现p站的解析，我只是手动添加到了最后。

**Comment by hoochanlon** [comment]
我的推测是：由于站点的CSP策略加载外部资源受限，也影响到了你的脚本执行程序加载，进而导致无法访问P站并报错ERR_EMPTY_RESPONSE，仅作一个参考

**Comment by URenko** [comment]
@ASC8384 目前代码仓库里的`dnscrypt/cloaking-rules.txt`没加P站，要手动加，至于不起效，也许是格式不对或者域名不对？

@hoochanlon 脚本在浏览器外，而且建立连接在CSP前，故并无关联，本issue大概是服务器的问题（如CDN）

**Comment by hoochanlon** [comment]
这个问题，的确有点意思，暂未定论前，目前还是持保留意见
https://www.firefox.net.cn/read-54107

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: URenko<mailto:notifications@github.com>
发送时间: 2020年4月15日 16:42
收件人: URenko/Accesser<mailto:Accesser@noreply.github.com>
抄送: 发霉的烂厘子<mailto:hoochanlon@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [URenko/Accesser] 访问P站提示ERR_EMPTY_RESPONSE (#80)


@ASC8384<https://github.com/ASC8384> 目前代码仓库里的dnscrypt/cloaking-rules.txt没加P站，要手动加，至于不起效，也许是格式不对或者域名不对？

@hoochanlon<https://github.com/hoochanlon> 脚本在浏览器外，而且建立连接在CSP前，故并无关联，本issue大概是服务器的问题（如CDN）

―

**Comment by ASC8384** [comment]
> 
> 
> @ASC8384 目前代码仓库里的`dnscrypt/cloaking-rules.txt`没加P站，要手动加，至于不起效，也许是格式不对或者域名不对？

使用[sysproxy](https://github.com/Noisyfox/sysproxy)后成功解决，谢谢！

~~p站的登录貌似有点问题~~

**Comment by URenko** [comment]
@ASC8384 暂时不用pull，<del>遥远的</del>未来打算做一些修改
登录问题是已知的，上面那位说的CSP可能是原因

**Comment by lxfly2000** [comment]
@ASC8384 感谢，我用你这个重新打包了一个一键运行程序
[accesser20200429.zip](https://github.com/URenko/Accesser/files/4551972/accesser20200429.zip)

**Comment by cssxsh** [comment]
> > @ASC8384 目前代码仓库里的`dnscrypt/cloaking-rules.txt`没加P站，要手动加，至于不起效，也许是格式不对或者域名不对？
> 
> 使用[sysproxy](https://github.com/Noisyfox/sysproxy)后成功解决，谢谢！
> 
> 分享下我的`dnscrypt/cloaking-rules.txt`，需要提个pull吗？
> 
> ```
> # Pixiv Start
> www.pixiv.net	210.140.131.203
> touch.pixiv.net	210.140.131.204
> source.pixiv.net	210.140.131.205
> accounts.pixiv.net	210.140.131.206
> imgaz.pixiv.net	210.140.131.207
> app-api.pixiv.net	210.140.131.208
> oauth.secure.pixiv.net	210.140.131.209
> dic.pixiv.net	210.140.131.210
> comic.pixiv.net	210.140.131.211
> factory.pixiv.net	210.140.131.212
> g-client-proxy.pixiv.net	18.211.61.121
> sketch.pixiv.net	210.140.170.179
> payment.pixiv.net	210.140.131.214
> sensei.pixiv.net	210.140.131.215
> novel.pixiv.net	210.140.131.216
> ssl.pixiv.net	210.140.131.217
> times.pixiv.net	66.6.32.22
> recruit.pixiv.net	210.140.131.218
> pixiv.net	210.140.131.219
> p2.pixiv.net	122.208.114.218
> matsuri.pixiv.net	13.35.19.186
> m.pixiv.net	210.140.131.220
> iracon.pixiv.net	13.35.19.88
> inside.pixiv.net	210.140.131.222
> i1.pixiv.net	210.140.131.223
> help.pixiv.net	210.140.131.224
> goods.pixiv.net	210.140.131.225
> genepixiv.pr.pixiv.net	210.140.131.226
> festa.pixiv.net	13.35.19.46
> en.dic.pixiv.net	210.140.131.180
> dev.pixiv.net	52.219.68.134
> chat.pixiv.net	210.140.131.181
> blog.pixiv.net	122.208.114.218
> embed.pixiv.net	210.140.131.182
> comic-api.pixiv.net	210.140.131.183
> pay.pixiv.net	210.140.131.184
> # Pixiv End
> ```
> 
> ~p站的登录貌似有点问题~

210.140.131 开头的Ip都是等效的 `210.140.131.{199..229}` 这个IP段是pixiv的 原生的IP地址段，也可以 `api.fanbox.cc` 代替，地址段是一样的，

其他的地址基本上都是cloudflare cdn 会有握手问题

**Comment by URenko** [comment]
stale
