### ISSUE TITLE
win版为什么只是一个exe文件?

### ISSUE THREAD

**Issue by joshatt** [URenko/Accesser#83]
不好意思,比较菜, 不明白怎么用------为什么只是一个exe文件, 想添加一个网站, 是修改template/pac文件吧? 但这个文件处于临时文件夹中, 并且文件夹名字是随机的. 关掉软件的话, 临时文件都消失了没法改

**Comment by URenko** [comment]
你要知道，有些人连解压都不会……
要修改的话，就不要用exe了，请看https://github.com/URenko/Accesser/wiki/开发者指南#开发环境的配置
