### ISSUE TITLE
访问维基百科提示该网页无法正常运作

### ISSUE THREAD

**Issue by softy9** [URenko/Accesser#84]
使用Chrome 提示zh.wikipedia.org 未发送任何数据。 ERR_EMPTY_RESPONSE

**Comment by URenko** [comment]
https://github.com/googlehosts/hosts/issues/248#issuecomment-632980110
请自行更换

**Comment by softy9** [comment]
研究了半天python，最后还是没搞懂操作方法，能否更新exe文件，谢谢

**Comment by liuxinyu970226** [comment]
建议维基媒体基金会网站们统一用issue 248处理，麻烦管理员合并过去

**Comment by ygsk10** [comment]
可用的 IP 可以在 [这个页面](https://zh.wikipedia.org/wiki/Help:%E5%A6%82%E4%BD%95%E8%AE%BF%E9%97%AE%E7%BB%B4%E5%9F%BA%E7%99%BE%E7%A7%91#%E7%BB%B4%E5%9F%BA%E5%AA%92%E4%BD%93%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%88%97%E8%A1%A8) 获取

**Comment by URenko** [comment]
#90
