### ISSUE TITLE
此工具是否可以和V2ray同时使用?

### ISSUE THREAD

**Issue by TianyuWong** [URenko/Accesser#86]
由于我有翻墙的需要, 又想利用该工具的功能直连WikiPedia以得到更快的速度, 因此我想知道有没有可能将此工具和V2ray的代理同时使用?
谢谢.

**Comment by ygsk10** [comment]
建议使用 [Clash](https://github.com/Dreamacro/clash) 分流

**Comment by URenko** [comment]
不借助Clash等三方工具直接改v2ray的配置文件也是可行的（实际上我就是这么干的）
