### ISSUE TITLE
请问一下我是linux应该怎么操作呢?

### ISSUE THREAD

**Issue by EndureBlaze** [URenko/Accesser#9]
因为你这里也没有写

**Comment by URenko** [comment]
1. clone或下载代码
2. 安装Python3.7
3. 安装依赖项：pyopenssl、doh-proxy
4. `python accesser.py -rr`以启动（可能要指定版本什么的，生成证书后以后就不用带-rr了）
5. 导入并信任`./CERT/root.crt`这个根证书
6. 配置PAC代理为`http://127.0.0.1:7654/pac/`
过几天我可能会写个详细点的

**Comment by nihaocun** [comment]
@URenko 我这边运行后提示没有doh proxy模块，很迷，系统是manjaro

**Comment by URenko** [comment]
doh-proxy安装了吗，可参考https://github.com/facebookexperimental/doh-proxy
`pip3 install doh-proxy`应该就能搞定安装吧
不过doh-proxy依赖的aioh2好像有些问题，我改了以下，可以
`pip3 install -U git+https://github.com/URenko/aioh2.git`以更新

**Comment by xihale** [comment]
截至目前，使用 aur 包是不会自动安装证书的，需要用以下命令
```
sudo trust anchor --store /usr/lib/pythonXXX/site-packages/accesser/CERT/root.crt
```
注意：`XXX` 取决于你的 `python --version`
我的是：
```
/usr/lib/python3.12/site-packages/accesser/CERT
```

**Comment by Sving1024** [comment]
> 截至目前，使用 aur 包是不会自动安装证书的，需要用以下命令
> 
> ```
> sudo trust anchor --store /usr/lib/pythonXXX/site-packages/accesser/CERT/root.crt
> ```
> 
> 注意：`XXX` 取决于你的 `python --version` 我的是：
> 
> ```
> /usr/lib/python3.12/site-packages/accesser/CERT
> ```

据我所知，证书是在程序第一次运行时候生成的。在安装的时候还没有证书，也就没有安装的时候自动安装证书这件事。如果真的在安装的时候附带了证书，货物我可以写一个post hook来支持。

另外打包问题不要反馈到上游。对于这种比较通用的问题，建议不要提及特定的发行版。

**Comment by xihale** [comment]
非常抱歉，我是看到他是 `manjaro` 才作此回复，并未考虑那么多。
安装的时候确实是不带证书的，如果要改变这个状况，也许可以使用 `openssl` 自签占用 `root` 证书文件，这样就可以在安装的时候安装证书？

**Comment by Sving1024** [comment]
感觉不是很符合kiss原则。通常此类操作都是用户手动进行的，毕竟大多数人都想知道自己信任了哪些证书。而且一般只有这一次需要导入。

**Comment by xihale** [comment]
我觉得这也是，要不在 `aur` 中加一个安装后的证书安装提示？

**Comment by URenko** [comment]
不用找证书路径，`curl http://localhost:7654/CERT/root.crt` 就是
Linux 信任证书太系统/应用相关了

**Comment by URenko** [comment]
> 请问，你觉得下面这条命令可以怎么改进
> 
> ```
> curl -O http://localhost:7654/CERT/root.crt && sudo trust anchor --store root.crt ; rm root.crt
> ```

不用 arch，感觉没毛病
