### ISSUE TITLE
建议添加GitHub

### ISSUE THREAD

**Issue by lxfly2000** [URenko/Accesser#99]
这不特殊时期嘛，GitHub前几天在部分地区开始间歇性抽风了，pac添加github.com后明显感觉好了很多，不排除以后被完全屏蔽……

**Comment by comet200403** [comment]
感觉现在github是被dns干扰了，目前在用学校的教育网DNS时感觉还可以

**Comment by xljiulang** [comment]
github还是留给[FastGithub](https://github.com/dotnetcore/FastGithub)来解决吧

**Comment by UjuiUjuMandan** [comment]
@xljiulang 怎么删库了？什么原因？讲讲。
